// Vocab for Wordle - 自动生成
// 5 难度 × 4 长度 = 20 个词库
// 总词数: ~8000+
const VOCAB = {
gaokao: {
4: ["ABLE","ALSO","AREA","ARMY","AWAY","BACK","BALL","BAND","BANK","BASE","BATH","BEAR","BEAT","BEEN","BELL","BEST","BIKE","BILL","BIRD","BITE","BLUE","BOAT","BODY","BOMB","BOND","BONE","BOOK","BORN","BOSS","BOTH","BOWL","BURN","BUSY","CAFE","CAKE","CALL","CALM","CAME","CAMP","CARD","CARE","CASE","CASH","CAST","CAUSE","CELL","CHAT","CHIP","CITY","CLUB","CLUE","COAL","COAT","CODE","COLD","COME","COOK","COOL","COPY","CORD","CORE","COST","CREW","CROP","DARK","DATA","DATE","DAWN","DEAD","DEAL","DEAR","DEBT","DEEP","DESK","DIAL","DICE","DIRT","DISK","DOCK","DOES","DONE","DOOR","DOWN","DRAG","DRAW","DREW","DROP","DRUM","DUAL","DUST","DUTY","EACH","EARL","EARN","EAST","EASY","EDGE","ELSE","EPIC","EVEN","EVER","EVIL","EXAM","EXIT","FACE","FACT","FAIL","FAIR","FALL","FAME","FARM","FAST","FATE","FEAR","FEED","FEEL","FEET","FELL","FELT","FILE","FILL","FILM","FIND","FINE","FIRE","FIRM","FISH","FIVE","FLAG","FLAT","FLED","FLEW","FLIP","FLOW","FOLD","FOLK","FOOD","FOOL","FOOT","FORD","FORE","FORK","FORM","FORT","FOUR","FREE","FROM","FUEL","FULL","FUND","GAIN","GAME","GANG","GATE","GAVE","GEAR","GENE","GIFT","GIRL","GIVE","GLAD","GOAL","GOES","GOLD","GOLF","GONE","GOOD","GRAB","GRAY","GREW","GREY","GROW","GULF","HAIR","HALF","HALL","HAND","HANG","HARD","HARM","HATE","HAVE","HEAD","HEAL","HEAP","HEAT","HEEL","HELD","HELL","HELP","HERE","HERO","HIGH","HILL","HINT","HIRE","HOLD","HOLE","HOLY","HOME","HOPE","HOST","HOUR","HUGE","HUNG","HUNT","HURT","ICON","IDEA","INCH","INTO","IRON","ITEM","JACK","JANE","JAZZ","JEAN","JOB","JOHN","JOIN","JOKE","JUMP","JUNE","JURY","JUST","KEEN","KEEP","KEPT","KEY","KICK","KILL","KIND","KING","KISS","KNEE","KNEW","KNIT","KNOW","LACK","LADY","LAID","LAKE","LAMP","LAND","LANE","LAST","LATE","LEAD","LEAF","LEAN","LEFT","LEND","LESS","LIFE","LIFT","LIKE","LINE","LINK","LIST","LIVE","LOAD","LOAN","LOCK","LOFT","LOGO","LONG","LOOK","LORD","LOSE","LOSS","LOST","LOTS","LOUD","LOVE","LUCK","MADE","MAIL","MAIN","MAKE","MALE","MANY","MARK","MASK","MASS","MATE","MAYS","MEAL","MEAN","MEAT","MEET","MENU","MERE","MESS","MIKE","MILD","MILE","MILK","MILL","MIND","MINE","MISS","MODE","MOOD","MOON","MORE","MOST","MOVE","MUCH","MUST","MYTH","NAIL","NAME","NAVY","NEAR","NEAT","NECK","NEED","NEWS","NEXT","NICE","NICK","NINE","NODE","NONE","NOON","NORM","NOSE","NOTE","NOUN","NUDE","NUTS","OATH","OBEY","ODDS","OKAY","ONCE","ONLY","ONTO","OPEN","ORAL","OURS","OVER","PACE","PACK","PAGE","PAID","PAIN","PAIR","PALE","PALM","PANT","PARK","PART","PASS","PAST","PATH","PEAK","PEEL","PEER","PICK","PINK","PIPE","PLAN","PLAY","PLOT","PLUG","PLUS","POEM","POET","POLE","POLL","POND","POOL","POOR","POPE","PORT","POSE","POST","POUR","PRAY","PULL","PUMP","PURE","PUSH","QUIT","QUIZ","RACE","RAFT","RAGE","RAID","RAIL","RAIN","RANK","RARE","RATE","READ","REAL","REAR","RELY","RENT","REST","RICE","RICH","RIDE","RING","RISE","RISK","ROAD","ROBE","ROCK","RODE","ROLE","ROLL","ROOF","ROOM","ROOT","ROPE","ROSE","ROWS","RULE","RUSH","RUTH","SAFE","SAID","SAKE","SALE","SALT","SAME","SAND","SANG","SAVE","SEAL","SEAT","SEED","SEEK","SEEM","SEEN","SELF","SELL","SEND","SENT","SEPT","SHED","SHIP","SHOP","SHOT","SHOW","SHUT","SICK","SIDE","SIGN","SILK","SILL","SING","SITE","SIZE","SKIN","SKIP","SLIP","SLOW","SNAP","SNOW","SOFT","SOIL","SOLD","SOLE","SOME","SONG","SOON","SORT","SOUL","SPAN","SPIN","SPIT","SPOT","STAR","STAY","STEM","STEP","STIR","STOP","SUCH","SUIT","SUNG","SURE","SWIM","TAIL","TAKE","TALE","TALK","TALL","TANK","TAPE","TASK","TEAM","TEAR","TELL","TEND","TENT","TERM","TEST","TEXT","THAN","THAT","THEM","THEN","THEY","THIN","THIS","THUS","TIDE","TIED","TILL","TIME","TINY","TIRE","TOES","TOLD","TONE","TOOK","TOOL","TOPS","TORE","TORN","TOUR","TOWN","TRAP","TREE","TRIM","TRIO","TRIP","TRUE","TUBE","TUCK","TUNE","TURN","TWIN","TYPE","UGLY","UNIT","UPON","USED","USER","VALE","VARY","VAST","VERB","VERY","VEST","VIEW","VOTE","WAGE","WAIT","WAKE","WALK","WALL","WANT","WARD","WARM","WARN","WASH","WAVE","WAYS","WEAK","WEAR","WEEK","WELL","WENT","WERE","WEST","WHAT","WHEN","WHOM","WIDE","WIFE","WILD","WILL","WIND","WINE","WING","WIRE","WISE","WISH","WITH","WOKE","WOLF","WOMAN","WOOD","WORD","WORE","WORK","WORM","WORN","WRAP","YARD","YEAH","YEAR","YELL","ZERO","ZONE"],
5: ["AAHED","ABACK","ABASE","ABATE","ABBEY","ABBOT","ABHOR","ABIDE","ABLED","ABODE","ABORT","ABOUT","ABUSE","ABYSS","ACORN","ACRID","ACTOR","ACUTE","ADAGE","ADAPT","ADEPT","ADMIN","ADMIT","ADOBE","ADOPT","ADORE","ADORN","ADULT","AFFIX","AFIRE","AFOOT","AFOUL","AFTER","AGAIN","AGAPE","AGATE","AGENT","AGILE","AGING","AGLOW","AGONY","AGREE","AHEAD","AIDED","AISLE","ALARM","ALBUM","ALERT","ALGAE","ALIBI","ALIEN","ALIGN","ALIKE","ALIVE","ALLAY","ALLEY","ALLOT","ALLOW","ALLOY","ALOFT","ALOHA","ALONE","ALONG","ALOOF","ALOUD","ALPHA","ALTAR","ALTER","AMASS","AMAZE","AMBER","AMBLE","AMEND","AMISS","AMITY","AMONG","AMPLE","AMPLY","AMUSE","ANGER","ANGLE","ANGRY","ANGST","ANIME","ANKLE","ANNEX","ANNOY","ANNUL","ANODE","ANTIC","ANVIL","AORTA","APART","APHID","APING","APNEA","APPLE","APPLY","APRON","APTLY","ARBOR","ARDOR","ARENA","ARGUE","ARISE","ARMED","AROMA","AROSE","ARRAY","ARROW","ARSON","ARTSY","ASCOT","ASHEN","ASIDE","ASKEW","ASSAY","ASSET","ATOLL","ATONE","AUDIO","AUDIT","AUGUR","AUNTY","AVAIL","AVERT","AVIAN","AVOID","AWAIT","AWAKE","AWARD","AWARE","AWASH","AWFUL","AWOKE","AXIAL","AXIOM","AZURE","BACON","BADGE","BADLY","BAGEL","BAGGY","BAKER","BALER","BALMY","BANAL","BANJO","BARGE","BARON","BASAL","BASIC","BASIL","BASIN","BASIS","BASTE","BATCH","BATHE","BATON","BATTY","BAWDY","BAYOU","BEACH","BEADY","BEAST","BEEFY","BEFIT","BEGAN","BEGAT","BEGET","BEGIN","BESET","BEZEL","BIBLE","BIDDY","BIGOT","BILGE","BILLY","BINGE","BINGO","BIOME","BIRCH","BIRTH","BISON","BITTY","BLACK","BLADE","BLAME","BLAND","BLANK","BLARE","BLAST","BLAZE","BLEAK","BLEAT","BLEED","BLEEP","BLEND","BLESS","BLIMP","BLIND","BLINK","BLISS","BLOAT","BLOCK","BLOKE","BLOND","BLOOD","BLOOM","BLOWN","BLUER","BLUFF","BLUNT","BLURB","BLURT","BOARD","BOAST","BOBBY","BONEY","BONGO","BONUS","BOOBY","BOOKS","BOOST","BOOTH","BOOTY","BOOZE","BOOZY","BORAX","BORNE","BOSOM","BOSSY","BOTCH","BOUGH","BOULE","BOUND","BOWEL","BOXER","BRACE","BRAID","BRAIN","BRAKE","BRAND","BRASH","BRASS","BRAVE","BRAVO","BRAWL","BRAWN","BREAD","BREAK","BREED","BRIAR","BRIBE","BRICK","BRIDE","BRIEF","BRINE","BRING","BRINK","BRINY","BRISK","BROAD","BROIL","BROKE","BROOD","BROOK","BROOM","BROTH","BROWN","BRUNT","BRUSH","BRUTE","BUDDY","BUDGE","BUGGY","BUGLE","BUILD","BUILT","BULGE","BULKY","BULLY","BUNCH","BUNNY","BURLY","BURNT","BURST","BUSED","BUSHY","BUTCH","BUTTE","BUZZY","BYLAW","CABIN","CABLE","CACAO","CACHE","CACTI","CADDY","CADET","CAGEY","CAIRN","CAMEL","CAMEO","CANAL","CANDY","CANNY","CANOE","CANON","CAPER","CAPUT","CARAT","CARGO","CAROL","CARRY","CARVE","CASTE","CATCH","CATER","CATTY","CAULK","CAUSE","CAVIL","CEASE","CEDAR","CELLO","CHAFE","CHAFF","CHAIN","CHAIR","CHALK","CHAMP","CHANT","CHAOS","CHARD","CHARM","CHART","CHASE","CHASM","CHEAP","CHEAT","CHECK","CHEEK","CHEER","CHESS","CHEST","CHICK","CHIDE","CHIEF","CHILD","CHILI","CHILL","CHIME","CHINA","CHIRP","CHOCK","CHOIR","CHOKE","CHORD","CHORE","CHOSE","CHUCK","CHUMP","CHUNK","CHURN","CHUTE","CIDER","CIGAR","CINCH","CIRCA","CIVIC","CIVIL","CLACK","CLAIM","CLAMP","CLANG","CLANK","CLASH","CLASP","CLASS","CLEAN","CLEAR","CLEAT","CLEFT","CLERK","CLICK","CLIFF","CLIMB","CLING","CLINK","CLOAK","CLOCK","CLONE","CLOSE","CLOTH","CLOUD","CLOUT","CLOVE","CLOWN","CLUCK","CLUMP","CLUNG","COACH","COAST","COBRA","COCOA","COLON","COLOR","COMET","COMFY","COMIC","COMMA","CONCH","CONDO","CONIC","COPSE","CORAL","CORER","CORNY","COUCH","COUGH","COULD","COUNT","COUPE","COURT","COVEN","COVER","COVET","COWED","COWER","CRACK","CRAFT","CRAMP","CRANE","CRANK","CRASH","CRASS","CRATE","CRAVE","CRAWL","CRAZE","CRAZY","CREAK","CREAM","CREDO","CREED","CREEK","CREEP","CREPT","CRESS","CREST","CRICK","CRIED","CRIER","CRIME","CRIMP","CRISP","CRISS","CROAK","CROCK","CRONE","CRONY","CROOK","CROSS","CROUP","CROWD","CROWN","CRUDE","CRUEL","CRUMB","CRUSH","CRUST","CRYPT","CUBIC","CUMIN","CURIO","CURLY","CURRY","CURSE","CURVE","CURVY","CUTIE","CYBER","CYCLE","CYNIC","DAFFY","DAILY","DAIRY","DAISY","DALLY","DANCE","DANDY","DATED","DATER","DATUM","DAUNT","DEALT","DEATH","DEBAR","DEBIT"],
6: ["ACCEPT","ACROSS","ACTION","ACTIVE","ACTUAL","AGREE","ALMOST","AMOUNT","ANNUAL","ANSWER","ANYONE","ANYWAY","APPEAR","AROUND","ARRIVE","ARTIST","ASPECT","ASSUME","ATTACK","AUGUST","BEAUTY","BECAME","BECOME","BEFORE","BEHALF","BEHIND","BELONG","BESIDE","BETTER","BEYOND","BITTER","BLANCH","BORDER","BOTTLE","BOTTOM","BRANCH","BREATH","BRIDGE","BRIGHT","BROKEN","BUDGET","BUTTON","CAMERA","CANCER","CARBON","CAREER","CASTLE","CAUGHT","CAUSE","CHANCE","CHANGE","CHARGE","CHOICE","CHOOSE","CHURCH","CIRCLE","CLEVER","CLOSE","CLOSET","COFFEE","COLUMN","COMBAT","COMING","COMMON","COOKIE","CORNER","COSTLY","COTTON","COUNT","COUPLE","COURSE","CREATE","CREDIT","CRISIS","CUSTOM","DAMAGE","DANGER","DEALER","DEBATE","DECADE","DECIDE","DEFEND","DEFINE","DEGREE","DEMAND","DEPEND","DEPUTY","DESERT","DESIGN","DESIRE","DETAIL","DEVICE","DIFFER","DINNER","DIRECT","DIVIDE","DOCTOR","DOMAIN","DOUBLE","DRIVEN","DRIVER","DURING","EASILY","EATING","EDITOR","EFFECT","EFFORT","EITHER","ENABLE","ENDING","ENERGY","ENGINE","ENOUGH","ENSURE","ENTIRE","EQUITY","ESCAPE","ESTATE","ETHNIC","EVENLY","EXCEPT","EXPAND","EXPECT","EXPERT","EXPORT","EXTEND","EXTENT","FABRIC","FACTOR","FAILED","FAIRLY","FALLEN","FAMILY","FARMER","FATHER","FAVOR","FELLOW","FIGURE","FILTER","FINGER","FLIGHT","FLOWER","FOLLOW","FORCED","FOREST","FORGET","FORMAL","FORMER","FOUGHT","FOURTH","FREEZE","FRIEND","FROZEN","FUTURE","GARDEN","GATHER","GENDER","GENTLY","GLOBAL","GOLDEN","GROUND","GROWTH","GUITAR","HANDLE","HAPPEN","HARDLY","HAVING","HEALTH","HEIGHT","HIDDEN","HIGHLY","HOLDER","HONEST","HORROR","IMPACT","IMPORT","IMPOSE","INCOME","INDEED","INJURY","INLAND","INSERT","INSIDE","INTEND","INVENT","INVEST","ISLAND","ITSELF","JERSEY","JUNIOR","KEEPER","LATEST","LATTER","LAUNCH","LAWYER","LEADER","LEAGUE","LEAVES","LEGEND","LENGTH","LESSON","LETTER","LITTLE","LIVING","LOCATE","LOSSES","LUXURY","MAKING","MANAGE","MANNER","MARKET","MASTER","MATTER","MEDIUM","MEMBER","MEMORY","MENTAL","MERELY","MERGER","METHOD","MIDDLE","MIGHTY","MINING","MINUTE","MIRROR","MOBILE","MODERN","MODEST","MOMENT","MOTHER","MOTION","MOVING","MURDER","MUSEUM","MUTUAL","NAMELY","NARROW","NATION","NATURE","NEARBY","NEATLY","NOBODY","NORMAL","NOTICE","NUMBER","OBJECT","OBTAIN","OFFEND","OFFICE","ONLINE","OPTION","ORANGE","ORIGIN","OUTFIT","OUTPUT","OXFORD","PACKED","PALACE","PARENT","PARTLY","PATENT","PATROL","PATTERN","PAYING","PEOPLE","PERIOD","PERMIT","PERSON","PHRASE","PICKUP","PIRATE","PLEASE","POCKET","POETRY","POISON","POLICE","POLICY","POSTAL","POWDER","PRAYER","PREFER","PRETTY","PRINCE","PRISON","PROFIT","PROPER","PROVEN","PUBLIC","PURSUE","RAISED","RANDOM","RARELY","RATHER","RATING","REASON","RECALL","RECENT","RECORD","REDUCE","REFORM","REGION","REJECT","RELATE","RELIEF","REMAIN","REMOTE","REMOVE","RENTAL","REPAIR","REPEAT","REPLY","REPORT","RESIGN","RESIST","RESORT","RESULT","RETAIL","RETAIN","RETIRE","RETURN","REVEAL","REVIEW","REWARD","RIDING","ROBUST","RULING","RUSHED","SCHOOL","SCREEN","SEARCH","SEASON","SECOND","SECRET","SECTOR","SECURE","SEEING","SELDOM","SELECT","SELLER","SENIOR","SERIES","SERVE","SETTLE","SEVERE","SHADOW","SHARED","SHIELD","SHORT","SHOULD","SHRINK","SIGHT","SIGNAL","SILENT","SIMPLE","SINGER","SINGLE","SISTER","SLEEVE","SMOOTH","SOCCER","SOCIAL","SOCKET","SOLDIER","SOUGHT","SOURCE","SPIRIT","SPOKEN","SPREAD","SPRING","SQUARE","STABLE","STATUS","STOLEN","STORED","STRAIN","STREAM","STREET","STRESS","STRICT","STROKE","STRONG","STUDIO","SUBMIT","SUDDEN","SUFFER","SUMMER","SUMMIT","SUPPLY","SURELY","SURVEY","SWITCH","SYMBOL","SYSTEM","TAKING","TARGET","TEMPLE","TENDER","THANKS","THEORY","THIRTY","THOUGH","THREAT","THROWN","TIMBER","TIMING","TISSUE","TOWARD","TRADE","TRAVEL","TREATY","TREND","TRIAL","TRIPLE","TROPHY","TRUCK","TWELVE","TWENTY","UNIQUE","UNLESS","UNLIKE","UPDATE","USEFUL","VALLEY","VICTIM","VISION","VOLUME","VOTING","WALKED","WALLET","WARMTH","WEALTH","WEAPON","WEEKLY","WHEELS","WHOLLY","WINDOW","WINTER","WISDOM","WITHIN","WONDER","WOODEN","WORKER","YELLOW"],
7: ["ABILITY","ACADEMY","ACCOUNT","ACCUSED","ACHIEVE","ACQUIRE","ADAPTER","ADDRESS","ADVISER","AGAINST","ALREADY","AMAZING","ANCIENT","ANOTHER","ANXIETY","ARTICLE","ATTEMPT","AUCTION","BALANCE","BATTERY","BECAUSE","BEDROOM","BENEFIT","BIGGEST","BLANKET","BUILDER","BURNING","CAPABLE","CAPTAIN","CAREFUL","CATALOG","CAUTION","CENTRAL","CHAPTER","CHARITY","CLASSIC","CLIMATE","CLOTHES","COLLEGE","COMPANY","COMPETE","COMPLEX","CONCEPT","CONCERN","CONCERT","CONDUCT","CONFIRM","CONNECT","CONSULT","CONTACT","CONTAIN","CONTENT","CONTROL","CONVERT","COOKING","CORRECT","COUNCIL","COUNTER","COUNTRY","CREATED","CREDIT","CRYSTAL","CULTURE","CURRENT","DEFENSE","DELIVER","DEPOSIT","DESKTOP","DIAMOND","DIGITAL","DINNER","DIPLOMA","DRAWING","DYNAMIC","EASTERN","ECONOMY","ELEMENT","EMOTION","ENDLESS","ENGLISH","EVENING","EXACTLY","EXAMINE","EXAMPLE","EXCITED","EXPLAIN","EXPLORE","EXPRESS","EXTREME","FACTORY","FACULTY","FAILURE","FASHION","FEATURE","FICTION","FIGHTER","FOREIGN","FORTUNE","FORWARD","FOUNDER","FREEDOM","FURTHER","GALLERY","GARDEN","GENERAL","GENETIC","GENUINE","GEOLOGY","GOODBYE","GRAPHIC","HABITAT","HALFWAY","HANGING","HARVEST","HEADING","HEALTHY","HEARING","HEAVEN","HERSELF","HIGHWAY","HISTORY","HOLIDAY","HONORED","HORIZON","HOSTING","HOUSING","HOWEVER","ILLNESS","IMAGINE","IMPROVE","INCLUDE","INDEED","INDUSTRY","INQUIRE","INSPECT","INSPIRE","INSTALL","INSTANT","INSTEAD","INTENSE","INTERIM","INVENT","INVITED","JOURNAL","JOURNEY","JUSTICE","KEEPING","KITCHEN","KNOWING","LARGELY","LASTING","LEATHER","LECTURE","LEGAL","LENDING","LENGTH","LIBERAL","LIBERTY","LIBRARY","LICENSE","LIFETIME","LIGHT","LIKEWISE","LIMITED","LISTEN","LOADING","LOCATED","LOGICAL","LOOKING","MACHINE","MANAGED","MANUAL","MARKET","MARTIAL","MATCHED","MAXIMUM","MEANING","MEASURE","MEDICAL","MEETING","MENTION","MILLION","MINERAL","MINIMUM","MIRACLE","MISTAKE","MIXTURE","MONITOR","MONTHLY","MORNING","NATURAL","NEAREST","NEITHER","NERVOUS","NETWORK","NEUTRAL","NOTABLE","NOTHING","NUCLEAR","NURSING","OBVIOUS","OFFENSE","OFFICER","OPERATE","OPINION","ORGANIC","OUTLINE","OUTLOOK","OUTSIDE","OVERALL","PACIFIC","PACKAGE","PAINTED","PANTHER","PARKING","PARTIAL","PARTNER","PASSAGE","PASSIVE","PATIENT","PATTERN","PAYMENT","PENALTY","PENSION","PEOPLE","PERFORM","PERHAPS","PHRASE","PIONEER","PITCHER","PLACING","PLASTIC","PLEASED","POINTER","POPULAR","PORTION","POVERTY","POWER","PRECISE","PREMIUM","PREPARE","PRESENT","PREVIEW","PRIMARY","PRINTER","PRIVATE","PROBLEM","PROCEED","PRODUCE","PRODUCT","PROFILE","PROGRAM","PROJECT","PROMISE","PROMOTE","PROPOSE","PROTECT","PROTEIN","PROTEST","PROVIDE","PUBLISH","PURPOSE","PUSHING","QUALIFY","QUALITY","QUARTER","QUIETLY","RADICAL","RANGING","READILY","READING","REALITY","REALIZE","RECEIVE","RECOVER","RECYCLE","REDUCED","REFER","REFLECT","REFUSED","REGULAR","RELATED","RELEASE","REMAINS","REMOVED","RENTING","REPLACE","REPORT","REQUEST","REQUIRE","RESERVE","RESOLVE","RESPECT","RESPOND","RESTORE","RETIRED","RETREAT","REVENUE","REVERSE","REVIVAL","ROUTINE","RUNNING","SCATTER","SCRATCH","SECTION","SELLING","SENDER","SERIOUS","SERVICE","SESSION","SETTING","SETTLED","SETTLER","SEVERAL","SHELTER","SHORTLY","SHOWING","SITTING","SKILLED","SMOKING","SOCIETY","SOMEHOW","SPEAKER","SPECIAL","SPONSOR","SPOTTER","STARTED","STARTUP","STATION","STOMACH","STRANGE","STUDENT","STUDIED","STUDIES","SUBJECT","SUCCEED","SUCCESS","SUGGEST","SUMMARY","SUPPORT","SURFACE","SURPLUS","SURPLUS","SURVIVE","SUSPEND","TEACHER","TELLING","TERRACE","TEXTILE","THEATER","THERAPY","TOBACCO","TRADING","TRAFFIC","TRAINED","TRAINER","TRUSTED","TURNING","TYPICAL","UNIFIED","UNKNOWN","UNUSUAL","UPGRADE","UTILITY","VARIETY","VARIOUS","VEHICLE","VENTURE","VERSION","VETERAN","VIEWING","VILLAGE","VIOLENT","WAITING","WALKING","WARNING","WEATHER","WEBSITE","WEDDING","WEEKEND","WELCOME","WELFARE","WESTERN","WHETHER","WILLING","WINNING","WITHOUT","WORKING","WRITING","WRITTEN"]
},
cet4: {
4: [],
5: ["DEBUG","DEBUT","DECAL","DECAY","DECOR","DECOY","DECRY","DEFER","DEIGN","DEITY","DELVE","DEMON","DEMUR","DENIM","DENSE","DEPOT","DEPTH","DERBY","DETER","DEVIL","DIARY","DICEY","DIGIT","DILLY","DIMLY","DINER","DINGO","DINGY","DIODE","DIRGE","DIRTY","DISCO","DITCH","DITTO","DITTY","DIVER","DIZZY","DODGE","DODGY","DOING","DOLLY","DONOR","DONUT","DOORS","DOPEY","DOUBT","DOUGH","DOWEL","DOWNY","DOWRY","DOZEN","DRAFT","DRAIN","DRAKE","DRAMA","DRANK","DRAPE","DRAWL","DRAWN","DREAD","DREAM","DRESS","DRIED","DRIER","DRIFT","DRILL","DRINK","DRIVE","DROIT","DROLL","DRONE","DROOL","DROOP","DROSS","DROVE","DROWN","DRUID","DRUNK","DRYER","DRYLY","DUCHY","DULLY","DUMMY","DUMPY","DUNCE","DUSKY","DUSTY","DUTCH","DUVET","DWARF","DWELL","DWELT","DYING","EAGER","EAGLE","EARLY","EARTH","EASEL","EATEN","EATER","EBONY","ECLAT","EDICT","EDIFY","EERIE","EGRET","EIGHT","EJECT","EKING","ELATE","ELBOW","ELDER","ELECT","ELEGY","ELFIN","ELIDE","ELITE","ELOPE","ELUDE","EMAIL","EMBED","EMBER","EMCEE","EMPTY","ENACT","ENDOW","ENEMA","ENEMY","ENJOY","ENNUI","ENSUE","ENTER","ENTRY","ENVOY","EPOCH","EQUAL","EQUIP","ERASE","ERECT","ERODE","ERROR","ERUPT","ESSAY","ESTER","ETHER","ETHIC","ETHOS","ETUDE","EVADE","EVENT","EVERY","EVICT","EVOKE","EXACT","EXALT","EXCEL","EXERT","EXILE","EXIST","EXTOL","EXULT","EYING","FABLE","FACET","FAINT","FAIRY","FAITH","FALSE","FANCY","FANNY","FARCE","FATAL","FATTY","FAULT","FAUNA","FAVOR","FEAST","FECAL","FEIGN","FELLA","FELON","FEMME","FEMUR","FENCE","FERAL","FERRY","FETAL","FETCH","FETID","FETUS","FEVER","FEWER","FIBER","FICUS","FIELD","FIEND","FIERY","FIFTH","FIFTY","FIGHT","FINAL","FINCH","FINER","FIRST","FISHY","FIXER","FIZZY","FJORD","FLACK","FLAIL","FLAIR","FLAKE","FLAKY","FLAME","FLANK","FLARE","FLASH","FLASK","FLECK","FLEET","FLESH","FLICK","FLIER","FLING","FLINT","FLIRT","FLOAT","FLOCK","FLOOD","FLOOR","FLORA","FLOSS","FLOUR","FLOUT","FLOWN","FLUFF","FLUID","FLUKE","FLUNG","FLUNK","FLUSH","FLUTE","FLYER","FOAMY","FOCAL","FOCUS","FOGGY","FOIST","FOLIO","FOLLY","FORAY","FORCE","FORGE","FORGO","FORTE","FORTH","FORTY","FORUM","FOUND","FOYER","FRAIL","FRAME","FRANK","FRAUD","FREAK","FREED","FREER","FRESH","FRIAR","FRIED","FRILL","FRISK","FRITZ","FROCK","FROND","FRONT","FROST","FROTH","FROWN","FROZE","FRUIT","FUDGE","FUGUE","FULLY","FUNGI","FUNKY","FUNNY","FUROR","FURRY","FUSSY","FUZZY","GAFFE","GAILY","GAMER","GAMMA","GAMUT","GAUDY","GAUGE","GAUNT","GAUZE","GAVEL","GAWKY","GAYLY","GECKO","GEESE","GENIE","GENRE","GHOST","GIANT","GIRTH","GIVEN","GIVER","GLADE","GLAND","GLARE","GLASS","GLEAM","GLEAN","GLOBE","GLOOM","GLORY","GLOSS","GLOVE","GLYPH","GNASH","GNOME","GODLY","GOING","GONAD","GOODY","GOOEY","GOOFY","GOOSE","GORGE","GOUGE","GOURD","GRACE","GRAFT","GRAIL","GRAIN","GRAND","GRANT","GRAPE","GRASP","GRASS","GRATE","GRAVE","GRAVY","GRAZE","GREAT","GREED","GREEN","GREET","GRIEF","GRILL","GRIME","GRIMY","GRIND","GRIPE","GROIN","GROOM","GROPE","GROSS","GROUP","GROUT","GROVE","GROWL","GROWN","GRUEL","GRUFF","GRUNT","GUARD","GUAVA","GUESS","GUEST","GUIDE","GUILD","GUILE","GUILT","GUISE","GULCH","GULLY","GUMBO","GUMMY","GUPPY","GUSTO","GUSTY","GYPSY","HABIT","HAIRY","HALVE","HANDY","HAPPY","HARDY","HAREM","HARPY","HARRY","HARSH","HATCH","HATER","HAUNT","HAVEN","HAVOC","HAZEL","HEART","HEAVY","HEDGE","HEFTY","HELIX","HELLO","HENCE","HERON","HILLY","HINGE","HIPPO","HIPPY","HITCH","HOARD","HOBBY","HOIST","HOLLY","HOMER","HONEY","HORDE","HORNY","HORSE","HOTEL","HOTLY","HOUND","HOUSE","HOVEL","HOVER","HOWDY","HUMAN","HUMID","HUMOR","HUMPH","HUMUS","HUNCH","HUNKY","HURRY","HUSKY","HUSSY","HUTCH","HYDRO","HYENA","HYMEN","HYPER","ICILY","ICING","IDEAL","IGLOO","ILIAC","IMAGE","IMBUE","IMPEL","INANE","INBOX","INCUR","INERT","INFER","INGOT","INLAY","INLET","INNER","INPUT","IONIC","IRATE","IRONY","ISLET","ISSUE","ITCHY","IVORY","JAUNT","JAZZY","JELLY","JERKY","JETTY","JEWEL","JIFFY","JOINT","JOIST","JOKER","JOLLY","JOUST","JUDGE","JUICE","JUICY","KAPPA","KARMA","KAYAK","KHAKI","KINKY","KIOSK","KITTY","KNAVE","KNEAD","KNEEL","KNELL","KNELT","KNIFE","KNOCK","KNOLL","KNOWN","KOALA","KRILL","LABEL","LABOR","LADEN","LADLE","LANCE","LANKY","LAPEL","LAPSE","LARGE","LARVA","LASER","LASSO","LATEX","LATHE","LAUGH","LAYER","LEACH","LEAFY","LEAKY","LEANT","LEAPY","LEARN","LEASE","LEASH","LEAST","LEAVE","LEDGE","LEECH","LEERY","LEFTY","LEGAL","LEGGY","LEMON","LIEGE","LIFER","LIGHT","LIKEN","LIMBO","LIMBS","LIMIT","LINEN","LINER","LINGO","LIPID","LITHE","LIVER","LLAMA","LOAMY","LOATH","LOBBY","LOCAL","LOCUS","LODGE","LOFTY","LOGIC","LOGIN","LOOPY","LOOSE","LORRY","LOSER","LOUSE","LOUSY","LOVER","LOWER","LOWLY","LUCID","LUMEN","LUMPY","LUNAR","LUNCH","LUNGE","LUPUS","LURCH","LURID","LUSTY","LYING","LYMPH","LYRIC","MACAW","MACHO","MACRO","MADAM","MADLY","MAFIA","MAGIC","MAIZE","MAJOR","MAKER","MAMBO","MAMMA","MAMMY","MANGA","MANGE","MANGO"],
6: ["ACCEPT","ACROSS","ACTION","ACTIVE","ACTUAL","AGREE","ALMOST","AMOUNT","ANNUAL","ANSWER","ANYONE","ANYWAY","APPEAR","AROUND","ARRIVE","ARTIST","ASPECT","ASSUME","ATTACK","AUGUST","BEAUTY","BECAME","BECOME","BEFORE","BEHALF","BEHIND","BELONG","BESIDE","BETTER","BEYOND","BITTER","BLANCH","BORDER","BOTTLE","BOTTOM","BRANCH","BREATH","BRIDGE","BRIGHT","BROKEN","BUDGET","BUTTON","CAMERA","CANCER","CARBON","CAREER","CASTLE","CAUGHT","CAUSE","CHANCE","CHANGE","CHARGE","CHOICE","CHOOSE","CHURCH","CIRCLE","CLEVER","CLOSE","CLOSET","COFFEE","COLUMN","COMBAT","COMING","COMMON","COOKIE","CORNER","COSTLY","COTTON","COUNT","COUPLE","COURSE","CREATE","CREDIT","CRISIS","CUSTOM","DAMAGE","DANGER","DEALER","DEBATE","DECADE","DECIDE","DEFEND","DEFINE","DEGREE","DEMAND","DEPEND","DEPUTY","DESERT","DESIGN","DESIRE","DETAIL","DEVICE","DIFFER","DINNER","DIRECT","DIVIDE","DOCTOR","DOMAIN","DOUBLE","DRIVEN","DRIVER","DURING","EASILY","EATING","EDITOR","EFFECT","EFFORT","EITHER","ENABLE","ENDING","ENERGY","ENGINE","ENOUGH","ENSURE","ENTIRE","EQUITY","ESCAPE","ESTATE","ETHNIC","EVENLY","EXCEPT","EXPAND","EXPECT","EXPERT","EXPORT","EXTEND","EXTENT","FABRIC","FACTOR","FAILED","FAIRLY","FALLEN","FAMILY","FARMER","FATHER","FAVOR","FELLOW","FIGURE","FILTER","FINGER","FLIGHT","FLOWER","FOLLOW","FORCED","FOREST","FORGET","FORMAL","FORMER","FOUGHT","FOURTH","FREEZE","FRIEND","FROZEN","FUTURE","GARDEN","GATHER","GENDER","GENTLY","GLOBAL","GOLDEN","GROUND","GROWTH","GUITAR","HANDLE","HAPPEN","HARDLY","HAVING","HEALTH","HEIGHT","HIDDEN","HIGHLY","HOLDER","HONEST","HORROR","IMPACT","IMPORT","IMPOSE","INCOME","INDEED","INJURY","INLAND","INSERT","INSIDE","INTEND","INVENT","INVEST","ISLAND","ITSELF","JERSEY","JUNIOR","KEEPER","LATEST","LATTER","LAUNCH","LAWYER","LEADER","LEAGUE","LEAVES","LEGEND","LENGTH"],
7: ["ABILITY","ACADEMY","ACCOUNT","ACCUSED","ACHIEVE","ACQUIRE","ADAPTER","ADDRESS","ADVISER","AGAINST","ALREADY","AMAZING","ANCIENT","ANOTHER","ANXIETY","ARTICLE","ATTEMPT","AUCTION","BALANCE","BATTERY","BECAUSE","BEDROOM","BENEFIT","BIGGEST","BLANKET","BUILDER","BURNING","CAPABLE","CAPTAIN","CAREFUL","CATALOG","CAUTION","CENTRAL","CHAPTER","CHARITY","CLASSIC","CLIMATE","CLOTHES","COLLEGE","COMPANY","COMPETE","COMPLEX","CONCEPT","CONCERN","CONCERT","CONDUCT","CONFIRM","CONNECT","CONSULT","CONTACT","CONTAIN","CONTENT","CONTROL","CONVERT","COOKING","CORRECT","COUNCIL","COUNTER","COUNTRY","CREATED","CREDIT","CRYSTAL","CULTURE","CURRENT","DEFENSE","DELIVER","DEPOSIT","DESKTOP","DIAMOND","DIGITAL","DINNER","DIPLOMA","DRAWING","DYNAMIC","EASTERN","ECONOMY","ELEMENT","EMOTION","ENDLESS","ENGLISH","EVENING","EXACTLY","EXAMINE","EXAMPLE","EXCITED","EXPLAIN","EXPLORE","EXPRESS","EXTREME","FACTORY","FACULTY","FAILURE","FASHION","FEATURE","FICTION","FIGHTER","FOREIGN","FORTUNE","FORWARD","FOUNDER","FREEDOM","FURTHER","GALLERY","GARDEN","GENERAL","GENETIC","GENUINE","GEOLOGY","GOODBYE","GRAPHIC","HABITAT","HALFWAY","HANGING","HARVEST","HEADING","HEALTHY","HEARING","HEAVEN","HERSELF","HIGHWAY","HISTORY","HOLIDAY","HONORED","HORIZON","HOSTING","HOUSING","HOWEVER","ILLNESS","IMAGINE","IMPROVE","INCLUDE","INDEED","INDUSTRY","INQUIRE","INSPECT","INSPIRE","INSTALL","INSTANT","INSTEAD","INTENSE","INTERIM","INVENT","INVITED","JOURNAL","JOURNEY","JUSTICE","KEEPING","KITCHEN","KNOWING","LARGELY"]
},
cet6: {
4: [],
5: ["MANGY","MANIA","MANIC","MANLY","MANOR","MARRY","MARSH","MASON","MASSE","MATCH","MATEY","MATTE","MAUVE","MAVEN","MAXIM","MAYBE","MAYOR","MEALY","MEANT","MEATY","MECCA","MEDAL","MEDIC","MELEE","MELON","MERCY","MERIT","MERRY","METAL","METER","METRO","MICRO","MIDST","MIGHT","MILKY","MIMIC","MINCE","MINER","MINIM","MINOR","MINTY","MINUS","MIRTH","MISER","MISSY","MOCHA","MODAL","MODEL","MODEM","MOGUL","MOIST","MOLAR","MOLDY","MONEY","MONTH","MOODY","MOOSE","MORAL","MORON","MORPH","MOSSY","MOTIF","MOTTO","MOULD","MOULT","MOUNT","MOURN","MOUSE","MOUTH","MOVER","MOVIE","MOWER","MUCKY","MUCUS","MUFTI","MUGGY","MULCH","MUMMY","MUNCH","MURAL","MURKY","MUSHY","MUSIC","MUSKY","MUSTY","MYRRH","NADIR","NAIVE","NANNY","NASAL","NASTY","NATAL","NAVAL","NAVEL","NEEDS","NEEDY","NERDY","NERVE","NEVER","NEWER","NEWLY","NICER","NICHE","NIFTY","NIGHT","NINJA","NINNY","NINTH","NOBLE","NORTH","NOVEL","NURSE","OASIS","OCEAN","OCTAL","OCTET","ODDER","ODDLY","OFFAL","OFFER","OFTEN","OLDEN","OLDER","OLIVE","OMBRE","OMEGA","ONION","ONSET","OPERA","OPINE","OPIUM","OPTIC","ORATE","ORBIT","ORDER","ORGAN","OTHER","OUGHT","OUNCE","OUTDO","OUTER","OUTGO","OUTRE","OUTRY","OVATE","OVERT","OVOID","OWING","OWNER","OXIDE","OZONE","PADDY","PAGAN","PAINT","PANEL","PANIC","PANSY","PANTO","PANTY","PAPAL","PAPER","PARED","PARKA","PARRY","PARSE","PARTY","PASTA","PASTE","PASTY","PATCH","PATER","PATTY","PAUSE","PAYEE","PAYER","PEACE","PEARL","PECAN","PEDAL","PENNE","PEONY","PERIL","PERKY","PESTO","PETAL","PHASE","PHONE","PHOTO","PIANO","PICCO","PIETY","PIGGY","PILOT","PITCH","PITHY","PIVOT","PIXEL","PIXIE","PIZZA","PLACE","PLAID","PLAIN","PLAIT","PLANE","PLANK","PLANT","PLATE","PLAZA","PLEAD","PLEAT","PLIED","PLOWS","PLUMB","PLUME","PLUMP","PLUMS","PLUSH","POACH","POEMS","POINT","POISE","POKER","POKEY","POLAR","POLED","POLIC","POLKA","POLOS","POLYP","PONDS","PONER","PONTS","POSED","POSER","POSES","POSIT","POSSE","POSTS","POTSY","POUCH","POUND","POUTS","POWER","PRANK","PREEN","PRESS","PREYS","PRICE","PRICK","PRIDE","PRIED","PRIES","PRIME","PRIMO","PRIMP","PRINT","PRION","PRIOR","PRISE","PRISM","PRIVY","PRIZE","PROBE","PROFS","PRONE","PRONG","PROOF","PROPS","PROSE","PROUD","PROVE","PROWL","PROXY","PRUDE","PRUNE","PSALM","PSYCH","PUBIC","PUDGY","PUFFY","PULPY","PULSE","PUMAS","PUNCH","PUNKS","PUNNY","PUNTO","PUNTS","PUPPY","PURGE","PURRS","PUSSY","PUTTY","PYGMY","QUACK","QUAIL","QUAIN","QUAKE","QUAKY","QUALM","QUARK","QUART","QUASH","QUAYS","QUEEN","QUEER","QUELL","QUERY","QUEST","QUEUE","QUICK","QUIDS","QUIET","QUIFF","QUILL","QUILT","QUIPS","QUIRE","QUIRK","QUIRT","QUITE","QUITS","QUOTA","QUOTE","QUOTH","RABBI","RABID","RACED","RACER","RACES","RACKS","RACON","RADAR","RADII","RADIO","RAFIA","RAFTS","RAGED","RAGES","RAILS","RAINS","RAINY","RAISE","RAJAH","RAKED","RAKES","RALLY","RAMPS","RANCH","RANDS","RANGE","RANGY","RANKS","RANTS","RAPED","RAPES","RAPID","RARER","RASPS","RATED","RATES","RATHE","RATIO","RATTY","RAVED","RAVEN","RAVER","RAVES","RAYED","RAZED","RAZOR","REACH","REACT","READS","READY","REALM","REAMS","REAPS","REARM","REARS","REBEL","REBUT","RECAP","RECON","RECUR","RECUT","REDDY","REDID","REDOS","REEDS","REEDY","REEFS","REFIT","REGAL","REIGN","REINS","RELAY","RELIC","REMIT","RENIN","RENTS","REPAY","REPEL","REPLY","RERAN","RERUN","RESET","RESIN","RETCH","RETRY","REUSE","REVEL","REVUE","RHEUM","RHINO","RHUMB","RIALS","RICED","RICER","RICES","RICHE","RICKS","RIDER","RIDES","RIDGE","RIFER","RIFLE","RIGHT","RIGID","RIGOR","RILED","RILES","RILLS","RIMED","RIMES","RINDS","RINGS","RINKS","RINSE","RIPEN","RIPER","RIPES","RISEN","RISER","RISES","RISKS","RISKY","RITES","RITZY","RIVED","RIVEN","RIVER","RIVES","ROACH","ROADS","ROAMS","ROANS","ROARS","ROAST","ROBED","ROBES","ROBIN","ROBOT","ROCKS","ROCKY","RODEO","ROGER","ROGUE","ROILS","ROLES","ROLLS","ROMAN","ROOFS","ROOKS","ROOMS","ROOMY","ROOST","ROOTS","ROPED","ROPES","ROPEY","ROSES","ROTOR","ROUGE","ROUGH","ROUND","ROUSE","ROUTE","ROUTS","ROVED","ROVER","ROVES","ROWAN","ROWED","ROWER","ROYAL","RUBLE","RUDDY","RUDER","RUFFS","RUGBY","RULER","RULES","RUMBA","RUMOR","RUMPS","RUNES","RUNGS","RUNIC","RUNNY","RUNTS","RUNTY","RUPEE","RURAL","RUSES","RUSHY","RUSTS","RUSTY","RUTTY","SABER","SABLE","SABRE","SACKS","SACRA","SADLY","SAFER","SAFES","SAGAS","SAGES","SAGGY","SAINT","SAKES","SALAD","SALES","SALLY","SALON","SALSA","SALTS","SALTY","SALVE","SALVO","SAMBA","SANDS","SANDY","SANED","SANER","SANES","SAPPY","SARAN","SARGE","SARIS","SASSY","SATAY","SATED","SATES","SATIN","SATYR","SAUCE","SAUCY","SAUNA","SAVED","SAVER","SAVES","SAVOR","SAVOY","SAWED","SAYER","SCABS","SCADS","SCALD","SCALE","SCALP","SCALY","SCAMP","SCANS","SCANT","SCARE","SCARF","SCARP","SCARS","SCARY","SCATS","SCENE","SCENT","SCION","SCOFF","SCOLD","SCONE","SCOOP","SCOOT","SCOPE","SCORE","SCORN","SCOUR","SCOUT","SCOWL","SCRAM","SCRAP","SCREE","SCREW"],
6: ["LESSON","LETTER","LITTLE","LIVING","LOCATE","LOSSES","LUXURY","MAKING","MANAGE","MANNER","MARKET","MASTER","MATTER","MEDIUM","MEMBER","MEMORY","MENTAL","MERELY","MERGER","METHOD","MIDDLE","MIGHTY","MINING","MINUTE","MIRROR","MOBILE","MODERN","MODEST","MOMENT","MOTHER","MOTION","MOVING","MURDER","MUSEUM","MUTUAL","NAMELY","NARROW","NATION","NATURE","NEARBY","NEATLY","NOBODY","NORMAL","NOTICE","NUMBER","OBJECT","OBTAIN","OFFEND","OFFICE","ONLINE","OPTION","ORANGE","ORIGIN","OUTFIT","OUTPUT","OXFORD","PACKED","PALACE","PARENT","PARTLY","PATENT","PATROL","PATTERN","PAYING","PEOPLE","PERIOD","PERMIT","PERSON","PHRASE","PICKUP","PIRATE","PLEASE","POCKET","POETRY","POISON","POLICE","POLICY","POSTAL","POWDER","PRAYER","PREFER","PRETTY","PRINCE","PRISON","PROFIT","PROPER","PROVEN","PUBLIC","PURSUE","RAISED","RANDOM","RARELY","RATHER","RATING","REASON","RECALL","RECENT","RECORD","REDUCE","REFORM","REGION","REJECT","RELATE","RELIEF","REMAIN","REMOTE","REMOVE","RENTAL","REPAIR","REPEAT","REPLY","REPORT","RESIGN","RESIST","RESORT","RESULT","RETAIL","RETAIN","RETIRE","RETURN","REVEAL","REVIEW","REWARD","RIDING","ROBUST","RULING","RUSHED","SCHOOL","SCREEN","SEARCH","SEASON","SECOND","SECRET","SECTOR","SECURE","SEEING","SELDOM","SELECT","SELLER","SENIOR","SERIES","SERVE","SETTLE","SEVERE","SHADOW","SHARED","SHIELD","SHORT","SHOULD","SHRINK","SIGHT","SIGNAL","SILENT","SIMPLE","SINGER","SINGLE","SISTER","SLEEVE","SMOOTH","SOCCER","SOCIAL","SOCKET","SOLDIER","SOUGHT","SOURCE","SPIRIT","SPOKEN","SPREAD","SPRING","SQUARE","STABLE","STATUS","STOLEN","STORED","STRAIN","STREAM","STREET","STRESS","STRICT","STROKE","STRONG","STUDIO","SUBMIT","SUDDEN","SUFFER","SUMMER","SUMMIT","SUPPLY","SURELY","SURVEY","SWITCH","SYMBOL","SYSTEM","TAKING","TARGET","TEMPLE","TENDER","THANKS","THEORY","THIRTY"],
7: ["LASTING","LEATHER","LECTURE","LEGAL","LENDING","LENGTH","LIBERAL","LIBERTY","LIBRARY","LICENSE","LIFETIME","LIGHT","LIKEWISE","LIMITED","LISTEN","LOADING","LOCATED","LOGICAL","LOOKING","MACHINE","MANAGED","MANUAL","MARKET","MARTIAL","MATCHED","MAXIMUM","MEANING","MEASURE","MEDICAL","MEETING","MENTION","MILLION","MINERAL","MINIMUM","MIRACLE","MISTAKE","MIXTURE","MONITOR","MONTHLY","MORNING","NATURAL","NEAREST","NEITHER","NERVOUS","NETWORK","NEUTRAL","NOTABLE","NOTHING","NUCLEAR","NURSING","OBVIOUS","OFFENSE","OFFICER","OPERATE","OPINION","ORGANIC","OUTLINE","OUTLOOK","OUTSIDE","OVERALL","PACIFIC","PACKAGE","PAINTED","PANTHER","PARKING","PARTIAL","PARTNER","PASSAGE","PASSIVE","PATIENT","PATTERN","PAYMENT","PENALTY","PENSION","PEOPLE","PERFORM","PERHAPS","PHRASE","PIONEER","PITCHER","PLACING","PLASTIC","PLEASED","POINTER","POPULAR","PORTION","POVERTY","POWER","PRECISE","PREMIUM","PREPARE","PRESENT","PREVIEW","PRIMARY","PRINTER","PRIVATE","PROBLEM","PROCEED","PRODUCE","PRODUCT","PROFILE","PROGRAM","PROJECT","PROMISE","PROMOTE","PROPOSE","PROTECT","PROTEIN","PROTEST","PROVIDE","PUBLISH","PURPOSE","PUSHING","QUALIFY","QUALITY","QUARTER","QUIETLY","RADICAL","RANGING","READILY","READING","REALITY","REALIZE","RECEIVE","RECOVER","RECYCLE","REDUCED","REFER","REFLECT","REFUSED","REGULAR","RELATED","RELEASE","REMAINS","REMOVED","RENTING","REPLACE","REPORT","REQUEST","REQUIRE","RESERVE","RESOLVE","RESPECT","RESPOND","RESTORE","RETIRED","RETREAT","REVENUE","REVERSE","REVIVAL"]
},
kaoyan: {
4: [],
5: ["SCRIM","SCRIP","SCROD","SCRUB","SCRUM","SCUBA","SCUFF","SCULL","SEALS","SEAMS","SEAMY","SEARS","SEATS","SEDAN","SEDER","SEEKS","SEEMS","SEEPS","SEERS","SEINE","SEIZE","SELLS","SENSE","SEPAL","SEPIC","SEPTA","SERFS","SERGE","SERIF","SERUM","SERVE","SEVEN","SEVER","SEWED","SEWER","SEXED","SEXES","SHACK","SHADE","SHADY","SHAFT","SHAGS","SHAHS","SHAKE","SHAKO","SHAKY","SHALE","SHALL","SHALT","SHAMS","SHANK","SHAPE","SHARD","SHARE","SHARK","SHARP","SHAVE","SHAWL","SHEAF","SHEAR","SHEEN","SHEEP","SHEER","SHEET","SHEIK","SHELF","SHELL","SHIED","SHIES","SHIFT","SHILL","SHIMS","SHINE","SHINS","SHINY","SHIPS","SHIRE","SHIRK","SHIRR","SHIRT","SHISH","SHIVA","SHIVE","SHOAL","SHOCK","SHOED","SHOES","SHOGI","SHONE","SHOOK","SHOOS","SHOOT","SHOPS","SHORE","SHORN","SHORT","SHOTS","SHOUT","SHOVE","SHOWN","SHOWS","SHOWY","SHRED","SHREW","SHRUB","SHRUG","SHUCK","SHUNT","SHUSH","SHUTS","SHYLY","SIDED","SIDES","SIDLE","SIEGE","SIEVE","SIFTS","SIGHS","SIGHT","SIGMA","SIGNS","SILKS","SILKY","SILLS","SILLY","SILOS","SILTS","SILTY","SINCE","SINGE","SINGH","SINGS","SINKS","SINUS","SIRED","SIRES","SISAL","SISSY","SITAR","SITED","SITES","SIXES","SIXTH","SIXTY","SIZED","SIZES","SKATE","SKEET","SKEIN","SKIDS","SKIED","SKIER","SKIES","SKIFF","SKILL","SKIMP","SKIMS","SKINK","SKINS","SKIPS","SKIRT","SKITS","SKULK","SKULL","SKUNK","SLABS","SLACK","SLAGS","SLAIN","SLAKE","SLAMS","SLANG","SLANT","SLAPS","SLASH","SLATE","SLATS","SLAVE","SLAVS","SLAYS","SLEDS","SLEEK","SLEEP","SLEET","SLEPT","SLEWS","SLICE","SLICK","SLIDE","SLIME","SLIMS","SLIMY","SLING","SLINK","SLIPS","SLITS","SLOBS","SLOES","SLOGS","SLOOP","SLOPE","SLOPS","SLOSH","SLOTH","SLUNG","SLUNK","SLURP","SLURS","SLUSH","SLYER","SMACK","SMALL","SMART","SMASH","SMEAR","SMELL","SMELT","SMILE","SMIRK","SMITE","SMITH","SMOCK","SMOGS","SMOKE","SMOKY","SMOTE","SMUTS","SNACK","SNAGS","SNAIL","SNAKE","SNAKY","SNAPS","SNARE","SNARL","SNEAK","SNEER","SNICK","SNIDE","SNIFF","SNIPE","SNIPS","SNITS","SNOBS","SNOOD","SNOOK","SNOOP","SNOOT","SNORE","SNORT","SNOTS","SNOUT","SNOWS","SNOWY","SNUBS","SNUCK","SNUFF","SNUGS","SOAKS","SOAPS","SOAPY","SOARS","SOBER","SOCKS","SODAS","SOFAS","SOGGY","SOILS","SOLAR","SOLDS","SOLED","SOLES","SOLID","SOLOS","SOLVE","SONAR","SONGS","SONIC","SONNY","SOONS","SOOTY","SOPHS","SOPPY","SORES","SORRY","SORTS","SOULS","SOUND","SOUPS","SOUPY","SOURS","SOWED","SOWER","SPACE","SPADE","SPAKE","SPANK","SPANS","SPARE","SPARK","SPARS","SPASM","SPATE","SPATS","SPAWN","SPEAK","SPEAR","SPECK","SPECS","SPEED","SPELL","SPELT","SPEND","SPENT","SPERM","SPEWS","SPICE","SPICY","SPIED","SPIEL","SPIES","SPIFF","SPIKE","SPIKY","SPILL","SPILT","SPINE","SPINS","SPINY","SPIRE","SPITE","SPITS","SPITZ","SPLAT","SPLAY","SPLIT","SPOIL","SPOKE","SPOOF","SPOOK","SPOOL","SPOON","SPOOR","SPORE","SPORT","SPOTS","SPOUT","SPRAT","SPRAY","SPREE","SPRIG","SPUDS","SPUME","SPUNK","SPURN","SPURS","SPURT","SQUAB","SQUAD","SQUAT","SQUAW","SQUIB","SQUID","STABS","STACK","STAFF","STAGE","STAGS","STAID","STAIN","STAIR","STAKE","STALE","STALK","STALL","STAMP","STAND","STANK","STAPH","STARE","STARK","STARS","START","STASH","STATE","STATS","STAVE","STAYS","STEAD","STEAK","STEAL","STEAM","STEED","STEEL","STEEP","STEER","STEIN","STEMS","STEPS","STERN","STEWS","STICK","STIES","STIFF","STILE","STILL","STILT","STING","STINK","STINT","STIRS","STOAT","STOCK","STOIC","STOKE","STOLE","STOMP","STONE","STONY","STOOD","STOOL","STOOP","STOPS","STORE","STORK","STORM","STORY","STOUT","STOVE","STOWS","STRAP","STRAW","STRAY","STREP","STREW","STRIP","STROP","STRUM","STRUT","STUBS","STUCK","STUDS","STUDY","STUFF","STUMP","STUNG","STUNK","STUNS","STUNT","STYLE","STYLI","STYMY","SUAVE","SUBAS","SUBBY","SUCHY","SUCKS","SUDAN","SUDSY","SUEDE","SUGAR","SULKS","SULKY","SULLY","SUMAC","SUMMA","SUNNY","SUNUP","SUPER","SURER","SURGE","SURLY","SUSHI","SWABS","SWAGS","SWAIN","SWAMI","SWAMP","SWANK","SWANS","SWAPS","SWARD","SWARM","SWASH","SWATH","SWATS","SWAYS","SWEAR","SWEAT","SWEEP","SWEET","SWELL","SWEPT","SWIFT","SWIGS","SWILL","SWIMS","SWINE","SWING","SWIPE","SWIRL","SWISH","SWISS","SWOON","SWOOP","SWORD","SWORE","SWORN","SWUNG","SYNOD","SYRUP","TABBY","TABLE","TABOO","TACIT","TACKS","TACKY","TACOS","TAILS","TAKEN","TAKER","TAKES","TALCS","TALES","TALKS","TALKY","TALLY","TALON","TAMED","TAMER","TAMES","TAMPS","TANGO","TANGS","TANGY","TANKS","TAPED","TAPER","TAPES","TAPIR","TARDY","TARED","TARES","TARGE","TARNS","TAROT","TARPS","TARRY","TARTS","TASKS","TASTE","TASTY","TATER","TAUNT","TAUTS","TAWNY","TAXED","TAXES","TAXIS","TEACH","TEALS","TEAMS","TEARS","TEARY","TEASE","TEATS","TECHS","TEDDY","TEEMS","TEENS","TEENY","TEETH","TELEX","TELIC","TELLS","TEMPI","TEMPO","TEMPT","TENDS","TENET","TENOR","TENSE","TENTH","TENTS","TEPEE","TEPID","TERMS","TERNS","TERSE","TESTS","TESTY","TEXTS","THANE","THANK","THAWS","THEFT","THEIR","THEME","THERE","THERM"],
6: ["THOUGH","THREAT","THROWN","TIMBER","TIMING","TISSUE","TOWARD","TRADE","TRAVEL","TREATY","TREND","TRIAL","TRIPLE","TROPHY","TRUCK","TWELVE","TWENTY","UNIQUE","UNLESS","UNLIKE","UPDATE","USEFUL","VALLEY","VICTIM","VISION","VOLUME","VOTING","WALKED","WALLET","WARMTH","WEALTH","WEAPON","WEEKLY","WHEELS","WHOLLY","WINDOW","WINTER","WISDOM","WITHIN","WONDER","WOODEN","WORKER","YELLOW"],
7: ["ROUTINE","RUNNING","SCATTER","SCRATCH","SECTION","SELLING","SENDER","SERIOUS","SERVICE","SESSION","SETTING","SETTLED","SETTLER","SEVERAL","SHELTER","SHORTLY","SHOWING","SITTING","SKILLED","SMOKING","SOCIETY","SOMEHOW","SPEAKER","SPECIAL","SPONSOR","SPOTTER","STARTED","STARTUP","STATION","STOMACH","STRANGE","STUDENT","STUDIED","STUDIES","SUBJECT","SUCCEED","SUCCESS","SUGGEST","SUMMARY","SUPPORT","SURFACE","SURPLUS","SURPLUS","SURVIVE","SUSPEND","TEACHER","TELLING","TERRACE","TEXTILE","THEATER","THERAPY","TOBACCO","TRADING","TRAFFIC","TRAINED","TRAINER","TRUSTED","TURNING","TYPICAL","UNIFIED","UNKNOWN","UNUSUAL","UPGRADE","UTILITY","VARIETY","VARIOUS","VEHICLE","VENTURE","VERSION","VETERAN","VIEWING","VILLAGE","VIOLENT","WAITING","WALKING","WARNING","WEATHER","WEBSITE","WEDDING","WEEKEND","WELCOME","WELFARE","WESTERN","WHETHER","WILLING","WINNING","WITHOUT","WORKING","WRITING","WRITTEN"]
},
ielts: {
4: [],
5: ["THESE","THETA","THICK","THIEF","THIGH","THINE","THING","THINK","THINS","THIRD","THONG","THORN","THOSE","THREE","THREW","THROB","THROW","THRUM","THUDS","THUGS","THUMB","THUMP","THYME","TIARA","TIBIA","TICKS","TIDAL","TIDED","TIDES","TIERS","TIFFS","TIGER","TIGHT","TILDE","TILED","TILER","TILES","TILLS","TILTS","TIMED","TIMER","TIMES","TIMID","TIPSY","TITAN","TITHE","TITLE","TIZZY","TOADS","TOADY","TOAST","TODAY","TODDY","TOFFY","TOGAS","TOILE","TOILS","TOKED","TOKEN","TOKES","TOLLS","TOMBS","TONES","TONGS","TONIC","TOOLS","TOOTH","TOOTS","TOPAZ","TOPIC","TORCH","TORES","TORSO","TORTS","TORUS","TOTAL","TOTED","TOTEM","TOTES","TOUCH","TOUGH","TOURS","TOUTS","TOWED","TOWEL","TOWER","TOXIC","TOXIN","TOYED","TRACE","TRACK","TRACT","TRADE","TRAIL","TRAIN","TRAIT","TRAMP","TRAMS","TRAPS","TRASH","TRAYS","TREAD","TREAT","TREED","TREES","TREKS","TREND","TRESS","TREYS","TRIAD","TRIAL","TRIBE","TRICE","TRICK","TRIED","TRIER","TRIES","TRIKE","TRILL","TRIMS","TRIOS","TRIPE","TRIPS","TRITE","TROLL","TROOP","TROPE","TROTH","TROTS","TROUT","TROVE","TRUCE","TRUCK","TRUES","TRULY","TRUMP","TRUNK","TRUSS","TRUST","TRUTH","TRYST","TUBAS","TUBBY","TUBED","TUBER","TUBES","TUCKS","TUFTS","TUFTY","TULIP","TULLE","TUMID","TUMMY","TUMOR","TUNED","TUNER","TUNES","TUNIC","TURBO","TURFS","TURFY","TURNS","TUSKS","TUTEE","TUTOR","TUTUS","TWAIN","TWANG","TWEAK","TWEED","TWEET","TWERP","TWICE","TWIGS","TWILL","TWINE","TWINS","TWIRL","TWIST","TWITS","TYING","TYKES","TYPED","TYPES","TYPIC","TYPOS","TYRED","TYRES","TZARS","UDDER","ULCER","ULTRA","UMBRA","UNCLE","UNCUT","UNDER","UNDID","UNDUE","UNFED","UNFIT","UNFIX","UNHIP","UNION","UNITE","UNITS","UNITY","UNLIT","UNMAN","UNSET","UNTIE","UNTIL","UNWED","UNZIP","UPEND","UPPED","UPPER","UPSET","URBAN","URGED","URGER","URGES","URINE","USERS","USHER","USING","USUAL","USURP","USURY","UTERI","UTILE","UTTER","UVULA","VAGUE","VAINS","VAIRS","VALES","VALET","VALID","VALOR","VALUE","VALVE","VAMPS","VANES","VAPID","VAPOR","VARIA","VASES","VAULT","VAUNT","VEALS","VEEPS","VEERS","VEILS","VEINS","VELDS","VELDT","VENAL","VENGE","VENOM","VENTS","VENUE","VERBS","VERGE","VERSE","VERSO","VERVE","VESTS","VEXED","VEXES","VIALS","VIAND","VIBES","VICAR","VICED","VICES","VIDEO","VIEWS","VIGIL","VIGOR","VILER","VILLA","VINES","VINYL","VIOLA","VIOLS","VIPER","VIRAL","VIRUS","VISAS","VISCS","VISIT","VISOR","VISTA","VITAL","VITAM","VIVER","VIVID","VIXEN","VIZIR","VOCAL","VODKA","VOGUE","VOICE","VOIDS","VOILE","VOLES","VOLTS","VOMIT","VOTED","VOTER","VOTES","VOUCH","VOWED","VOWEL","VOWER","VROOM","VYING","WACKO","WACKY","WADDY","WADED","WADER","WADES","WADIS","WAFER","WAFTS","WAGED","WAGER","WAGES","WAGON","WAIFS","WAILS","WAIST","WAITS","WAIVE","WAKED","WAKEN","WAKES","WALKS","WALLS","WALTZ","WANDS","WANED","WANES","WANGS","WANTS","WARDS","WARES","WARMS","WARNS","WARPS","WARTS","WARTY","WASHY","WASPS","WASTE","WATCH","WATER","WATTS","WAVED","WAVER","WAVES","WAVEY","WAXED","WAXEN","WAXES","WEARS","WEARY","WEAVE","WEDGE","WEDGY","WEEDS","WEEDY","WEEKS","WEEPS","WEEPY","WEFTS","WEIGH","WEIRD","WELDS","WELLS","WELTS","WENCH","WENDS","WESTS","WETLY","WHACK","WHALE","WHAMS","WHANG","WHARF","WHEAT","WHEEL","WHELK","WHELM","WHENS","WHERE","WHETS","WHICH","WHIFF","WHILE","WHIMS","WHINE","WHINY","WHIPS","WHIRL","WHIRR","WHIRS","WHISK","WHIST","WHITE","WHITS","WHIZZ","WHOLE","WHOMP","WHOMS","WHORE","WHORL","WHOSE","WICKS","WIDED","WIDER","WIDES","WIDOW","WIDTH","WIELD","WIGHT","WIKIS","WILDS","WILES","WILLS","WILLY","WILTS","WIMPS","WIMPY","WINCE","WINCH","WINDS","WINDY","WINED","WINES","WINGS","WINKS","WINOS","WIPED","WIPER","WIPES","WIRED","WIRES","WIREY","WISER","WISES","WISHY","WISPS","WISPY","WITCH","WITHE","WITTY","WIVES","WOKEN","WOLFS","WOMAN","WOMBS","WOMEN","WOODY","WOOED","WOOER","WOOFS","WORLD","WORST","WORTH","WOULD","WOUND","WOVEN","WRACK","WRAPS","WRATH","WREAK","WRECK","WRENS","WREST","WRIST","WRITE","WRITS","WROTE","WROTH","WRUNG","WRYLY","WUSSY","XENON","YACHT","YANKS","YARDS","YARNS","YAWLS","YAWNS","YEARN","YEARS","YEAST","YELLS","YELPS","YESES","YIELD","YIPES","YODEL","YOGAS","YOGIC","YOGIS","YOKED","YOKEL","YOKES","YOLKS","YOLKY","YOUNG","YOURS","YOUTH","YOWLS","YOYOS","YUCCA","YUCKS","YUHAN","YUMMY","YUPPY","ZAIRE","ZAPPY","ZEALS","ZEBRA","ZEROS","ZESTY","ZILCH","ZILLS","ZINCS","ZINGS","ZINGY","ZIPPY","ZONAL","ZONED","ZONES","ZOOMS","ZOOTY","ABYSS","ACRID","ADAGE","ADEPT","ADIEU","AGAPE","AGOGO","AHULL","AIMER","ALOOF","AMITY","ANIME","ANNEX","ANTIC","AORTA","AUDIO","AURIC","AZURE","BADGE","BAFFY","BANAL","BARGE","BATIK","BATON","BEGET","BEQUE","BIDET","BILGE","BISON","BLITZ","BLOND","BLUFF","BLURT","BOGUS","BONUS","BORAX","BOTCH","BRASH","BRAWN","BRIAR","BRINE","BROIL","BRUNT","BUDDY","BUGGY","BUXOM","CABAL","CADET","CAGEY","CANDY","CANTON","CAPER","CARAT","CARGO","CARVE","CATCH","CATER","CAULK","CAVIL","CEASE","CECUM","CHAMP","CHANT","CHARD","CHARM","CHART","CHASE","CHASM","CHESS","CHEST","CHIDE","CHIME","CHIRP","CHOIR","CHORD","CHORE","CHOSE","CHURN","CIVIC","CLEFT","CLERK","CLICK","CLIFF","CLIME","CLINK","CLONE","CLOTH","CLOUT","CLOVE","CLOVER","CLUMP","CLUNK","COACH","COAST","COCOA","COLIC","COMET","COMIC","COMMA","CONCH","CONDO","CONE","COO","COPSE","CORGI","COUGH","COULD","COUNT","COUPE","COVEN","COVER","COVET","COWER","CRAMP","CRANE","CRASH","CRAVE","CRAZE","CREAK","CREDO","CREED","CREEK","CREPE","CRESS","CREST","CRICK","CRIME","CRIMP","CRISP","CROCK","CRONE","CROOK","CROSS","CROWD","CRUDE","CRUEL","CRUMB","CRUST","CRYPT","CUMIN","CUPID","CURIO","CURRY","CURSE","CURVE","CUTIE","CYCLE","DADDY","DANDY","DARED","DATUM","DAUNT","DEBAR","DECAL","DECAY","DECOR","DECOY","DELVE","DEMUR","DEPOT","DESK","DIARY","DICEY","DIGIT","DINGY","DIODE","DIRGE","DITCH","DIVER","DODGE","DOILY","DONOR","DOSSIER","DOTTY","DOUGH","DOWDY","DOWEL","DOWRY","DOZEN","DRAFT","DRAIN","DREAD","DREAM","DRESS","DRIED","DRIER","DRIFT","DRILL","DRINK","DRIVE","DROIT","DROLL","DRONE","DROOP","DROVE","DROWN","DRUID","DRUNK","DRYLY","DUCAL","DUCAT","DUCHY","DULLY","DUMMY","DUMPY","DUNCE","DUSKY","DUTCH","DUVET","DWARF","DWELL","EAGER","EAGLE","EARLY","EARTH","EATER","EBONY","EDICT","EDIFY","EERIE","EGRET","EIGHT","EJECT","ELBOW","ELDER","ELECT","ELEGY","ELITE","ELOPE","ELUDE","ELVER","EMBER","EMCEE","EMPTY","ENACT","ENROL","ENSUE","ENTER","EPOCH","EPOQUE","EQUAL","EQUIP","ERECT","ERODE","ERUPT","ESSAY","ETHER","ETHIC","ETHOS","EVOKE","EXACT","EXALT","EXILE","EXIST","EXPEL","EXTOL","EXULT","EYING","FABLE","FACET","FADE","FAITH","FALSE","FANCY","FANNY","FAULT","FAUNA","FAVOR","FEAST","FECAL","FEIGN","FELON","FEMME","FEMUR","FENCE","FERAL","FERRY","FETAL","FETCH","FETID","FETUS","FEVER","FIBER","FIELD","FIEND","FIFTH","FIGHT","FILER","FILET","FILLY","FILMY","FILTH","FINAL","FINCH","FINER","FIRST","FISHY","FIXER","FJORD","FLACK","FLAIR","FLAKE","FLAME","FLANK","FLARE","FLASH","FLASK","FLAT","FLAW","FLECK","FLEECE","FLESH","FLICK","FLIER","FLINT","FLIRT","FLOAT","FLOCK","FLOOD","FLOOR","FLORA","FLOSS","FLOUR","FLOUT","FLOWN","FLUFF","FLUID","FLUKE","FLUME","FLUNK","FLUSH","FLUTE","FOAL","FOAM","FOCAL","FOCUS","FOGGY","FOIST","FOLIO","FOLLY","FORAY","FORCE","FORGE","FORGO","FORTE","FORTH","FORTY","FORUM","FOUND","FOYER","FRAIL","FRAME","FRANK","FRAT","FRAUD","FREAK","FREED","FREER","FRESH","FRIAR","FRILL","FRISK","FRITZ","FROCK","FROND","FRONT","FROST","FROTH","FROWN","FROZE","FRUIT","FUDGE","FUGUE","FULLY","FUMED","FUNDY","FUNGI","FUNKY","FUNNY","FUROR","FURRY","FUSSY","FUZZY","GAFFE","GAGNE","GAILY","GAMER","GAMMA","GAMUT","GASSY","GAUDY","GAUGE","GAUNT","GAUZE","GAWKY","GAYER","GAYLY","GAZE","GECKO","GEEKY","GOOSE","GORGE","GOUGE","GOURD","GRACE","GRADE","GRAFT","GRAIL","GRAIN","GRAND","GRANT","GRAPE","GRAPH","GRASP","GRASS","GRATE","GRAVE","GRAVY","GRAZE","GREAT","GREED","GREEN","GREET","GRIEF","GRILL","GRIME","GRIMY","GRIND","GRIP","GROAN","GROIN","GROOM","GROPE","GROSS","GROUP","GROUT","GROVE","GROWL","GROWN","GRUEL","GRUFF","GRUNT","GUARD","GUAVA","GUILD","GUILE","GUILT","GUISE","GULCH","GULLY","GUMMY","GUPPY","GUSTO","GUSTY","GYPSY","HABIT","HAIRY","HALON","HANDY","HAPPY","HARDY","HAREM","HARPY","HARRY","HARSH","HASTE","HASTY","HATCH","HATER","HAUNT","HAUTE","HAVEN","HAZEL","HEADY","HEARD","HEART","HEATH","HEAVE","HEAVY","HEDGE","HEFTY","HEIST","HELIX","HELLO","HENCE","HERON","HILLY","HINGE","HIPPO","HIPPY","HITCH","HOARD","HOBBY","HOIST","HOMER","HONEY","HONOR","HORDE","HORNY","HORSE","HOSTA","HOTEL","HOTLY","HOUND","HOUSE","HOVER","HOWDY","HULLY","HUMAN","HUMID","HUMOR","HUMPH","HUMUS","HUNCH","HUNKY","HURRY","HUSKY","HUSSY","HUTCH","HYDRO","HYENA","HYMEN","HYPER","ICILY","ICING","IDEAL","IDIOM","IDLER","IDYLL","IGLOO","ILIAC","IMAGE","IMBUE","IMPEL","IMPLY","INANE","INBOX","INCUR","INDEX","INERT","INFER","INGOT","INLAY","INLET","INNER","INPUT","INTER","INTRO","IONIC","IRATE","IRONY","ISLET","ISSUE","ITCHY","IVORY","JAUNT","JAZZY","JELLY","JERKY","JETTY","JEWEL","JIFFY","JOINT","JOIST","JOKER","JOLLY","JOUST","JUDGE","JUICE","JUICY","JUMBO","JUMPY","JUNTA","JUROR","KAPPA","KARMA","KAYAK","KEBAB","KHAKI","KIOSK","KITTY","KNACK","KNAVE","KNEAD","KNEEL","KNELT","KNIFE","KNOCK","KNOLL","KNOWN","KOALA","KRILL","LABEL","LABOR","LADEN","LADLE","LAGER","LANCE","LANKY","LAPEL","LAPSE","LARGE","LARVA","LASSO","LATCH","LATER","LATHE","LATTE","LAUGH","LAYER","LEACH","LEAFY","LEAKY","LEAN","LEAPT","LEARN","LEASE","LEASH","LEAST","LEAVE","LEDGE","LEECH","LEERY","LEFTY","LEGAL","LEMON","LEMUR","LEPER","LEVEL","LIABLE","LIBEL","LIEGE","LIGHT","LIKEN","LILAC","LIMIT","LINEN","LINER","LINGO","LIPID","LITHE","LIVER","LIVID","LLAMA","LOAMY","LOATH","LOBBY","LOCAL","LOCUS","LODGE","LOFTY","LOGIC","LOGIN","LOOPY","LOOSE","LORRY","LOSER","LOUSY","LOVER","LOWER","LOWLY","LOYAL","LUCID","LUCKY","LUMEN","LUMPY","LUNAR","LUNCH","LUNGE","LUPUS","LURCH","LURID","LUSTY","LYING","LYMPH","LYRIC","MACAW","MACHO","MACRO","MADAM","MADLY","MAFIA","MAGIC","MAGMA","MAIZE","MAJOR","MAKER","MAMBA","MAMBO","MAMMA","MAMMY","MANGA","MANGO","MANGY","MANIA","MANIC","MANLY","MANOR","MAPLE","MARCH","MARRY","MARSH","MASON","MASSE","MATCH","MATEY","MAUVE","MAXIM","MAYBE","MAYOR","MEALY","MEANT","MEATY","MECCA","MEDAL","MEDIA","MEDIC","MELEE","MELON","MERCY","MERGE","MERIT","MERRY","METAL","METER","METRO","MICRO","MIDGE","MIDST","MIGHT","MILKY","MIMIC","MINCE","MINER","MINIM","MINOR","MINTY","MINUS","MIRTH","MISER","MISSY","MOCHA","MODAL","MODEL","MODEM","MOGUL","MOIST","MOLAR","MOLDY","MOMMY","MONEY","MONTH","MOODY","MOOSE","MORAL","MORON","MORPH","MOSSY","MOTEL","MOTIF","MOTOR","MOTTO","MOULT","MOUND","MOUNT","MOURN","MOUSE","MOUTH","MOVER","MOVIE","MOWER","MUCKY","MUCUS","MUDDY","MULCH","MUMMY","MUNCH","MURAL","MURKY","MUSHY","MUSIC","MUSKY","MUSTY","MYRRH","NADIR","NAIVE","NANNY","NASAL","NASTY","NATAL","NAVAL","NAVEL","NEEDY","NEIGH","NERDY","NERVE","NEVER","NEWER","NEWLY","NICER","NICHE","NIECE","NIGHT","NINJA","NINTH","NOBLE","NOBLY","NOISE","NOISY","NOMAD","NOOSE","NORTH","NOSEY","NOTCH","NOVEL","NUDGE","NURSE","NUTTY","NYLON","NYMPH","OAKEN","OBESE","OCCUR","OCEAN","OCTET","ODDER","ODDLY","OFFAL","OFFER","OFTEN","OLDER","OLIVE","OMBRE","OMEGA","ONION","ONSET","OPERA","OPINE","OPIUM","OPTIC","ORBIT","ORDER","ORGAN","OTHER","OTTER","OUGHT","OUNCE","OUTDO","OUTER","OUTGO","OVARY","OVATE","OVERT","OVINE","OVOID","OWING","OWNER","OXIDE","OZONE","PADDY","PAGAN","PAINT","PALER","PALSY","PANEL","PANIC","PANSY","PANTS","PAPAL","PAPER","PARER","PARKA","PARRY","PARSE","PARTY","PASTA","PASTE","PASTY","PATCH","PATIO","PAUSE","PAYEE","PAYER","PEACE","PEACH","PEARL","PECKS","PEDAL","PENAL","PENCE","PENNY","PERCH","PERIL","PERKY","PESKY","PESTO","PETAL","PETTY","PHASE","PHONE","PHOTO","PIANO","PICKY","PIECE","PIETY","PIGGY","PILOT","PINCH","PINEY","PINKY","PINTO","PIPER","PIQUE","PITCH","PITHY","PIVOT","PIXEL","PIXIE","PIZZA","PLACE","PLAID","PLAIN","PLAIT","PLANE","PLANK","PLANT","PLATE","PLAZA","PLEAD","PLEAT","PLIED","PLIER","PLUCK","PLUMB","PLUME","PLUNK","PLUSH","POESY","POINT","POISE","POKER","POLAR","POLKA","POLYP","POOCH","POPPY","PORCH","POSER","POSIT","POSSE","POUCH","POUND","POWER","PRANK","PRAWN","PREEN","PRESS","PRICE","PRICK","PRIDE","PRIED","PRIME","PRIMO","PRINT","PRIOR","PRISM","PRIVY","PRIZE","PROBE","PRONE","PRONG","PROOF","PROSE","PROUD","PROVE","PROWL","PROXY","PRUDE","PRUNE","PSALM","PUBIC","PUDGY","PULSE","PUNCH","PUPIL","PUPPY","PURGE","PURSE","PUSHY","PUTTY","PYGMY","QUACK","QUAIL","QUAKE","QUALM","QUARK","QUART","QUASH","QUASI","QUEEN","QUEER","QUELL","QUERY","QUEST","QUEUE","QUICK","QUIET","QUILL","QUILT","QUINT","QUIP","QUIRE","QUIRK","QUITE","QUOTA","QUOTE","RABBI","RABID","RACER","RADAR","RADII","RADIO","RADON","RAGED","RAGEE","RAINY","RAISE","RAJAH","RALLY","RALPH","RAMEN","RANGE","RANEE","RANK","RANSOM","RARED","RASP","RATIO","RATTY","RAVEN","RAYON","RAZOR","REACH","REACT","READY","REALM","REARM","REBAR","REBEL","REBUS","REBUT","RECAP","RECON","RECTO","RECUR","RECUT","REDID","REEDY","REFER","REFIT","REGAL","REIGN","RELAX","RELAY","RELIC","REMIX","RENAL","RENEW","REPAY","REPEL","REPLY","RERUN","RESET","RESIN","RETCH","RETRO","RETRY","REUSE","REVEL","REVUE","RHINO","RHYME","RIDER","RIDGE","RIFLE","RIGHT","RIGID","RIGOR","RINSE","RIPEN","RIPER","RISEN","RISER","RISKY","RIVAL","RIVER","RIVET","ROACH","ROAST","ROBIN","ROBOT","ROCKY","ROGER","ROGUE","ROOMY","ROOST","ROTOR","ROUGE","ROUGH","ROUND","ROUSE","ROUTE","ROVER","ROWDY","ROWER","ROYAL","RUDER","RUGBY","RULER","RUMBA","RUMOR","RUPEE","RURAL","RUSTY","SADLY","SAFER","SAINT","SALAD","SALES","SALON","SANDY","SANER","SASSY","SATIN","SAUCY","SAUNA","SAVOR","SAVVY","SCALD","SCALE","SCALP","SCALY","SCAMP","SCANT","SCARE","SCARF","SCARY","SCENE","SCENT","SCHWA","SCOLD","SCONE","SCOOP","SCOOT","SCOPE","SCORE","SCORN","SCOUR","SCOUT","SCOWL","SCRAM","SCRAP","SCREE","SCREW","SCRUB","SEDAN","SEEDY","SERVE","SEVEN","SEVER","SEWER","SHACK","SHADE","SHADY","SHAFT","SHAKE","SHAKY","SHALE","SHALL","SHAME","SHANK","SHAPE","SHARD","SHARE","SHARK","SHARP","SHAVE","SHAWL","SHEAR","SHEEN","SHEEP","SHEER","SHEET","SHEIK","SHELF","SHELL","SHINY","SHIRE","SHIRK","SHIRT","SHOAL","SHOCK","SHONE","SHOOK","SHOOT","SHORE","SHORN","SHORT","SHOUT","SHOVE","SHOWN","SHOWY","SHRED","SHRUB","SHRUG","SHUCK","SHUNT","SHUSH","SHYLY","SIEGE","SIGHT","SIGMA","SILKY","SILLY","SILVA","SINCE","SINEW","SINGE","SIREN","SIRUP","SISSY","SIXTH","SIXTY","SKATE","SKIER","SKIFF","SKILL","SKIMP","SKIRT","SKULK","SKULL","SKUNK","SLACK","SLAIN","SLANG","SLANT","SLASH","SLATE","SLEEK","SLEEP","SLEET","SLICE","SLICK","SLIDE","SLIME","SLIMY","SLING","SLINK","SLOPE","SLOSH","SLOTH","SLUMP","SLUNG","SLUNK","SLURP","SLUSH","SLYLY","SMACK","SMALL","SMART","SMASH","SMEAR","SMELL","SMELT","SMILE","SMIRK","SMITE","SMITH","SMOCK","SMOKE","SMOKY","SMOTE","SNAFU","SNAIL","SNAKE","SNAKY","SNARE","SNARL","SNEAK","SNEER","SNIDE","SNIFF","SNIPE","SNOOP","SNORE","SNORT","SNOUT","SNOWY","SNUFF","SOAPY","SOBER","SOGGY","SOLAR","SOLID","SOLVE","SONAR","SONIC","SOOTH","SOOTY","SORER","SORRY","SOUND","SOUPY","SOUSE","SOUTH","SOWER","SPACE","SPADE","SPANK","SPARE","SPARK","SPASM","SPEAR","SPECK","SPEED","SPELL","SPEND","SPENT","SPERM","SPICE","SPICK","SPIED","SPIEL","SPIKE","SPIKY","SPILL","SPILT","SPINE","SPINY","SPIRE","SPITE","SPLAT","SPLAY","SPLIT","SPOIL","SPOKE","SPOOF","SPOOK","SPOOL","SPOON","SPORE","SPORT","SPOUT","SPRAY","SPREE","SPRIG","SPUNK","SPURN","SPURT","SQUAD","SQUAT","SQUIB","STACK","STAFF","STAGE","STAID","STAIN","STAIR","STAKE","STALE","STALK","STALL","STAMP","STAND","STANK","STARE","STARK","START","STASH","STATE","STAVE","STEAD","STEAK","STEAL","STEAM","STEED","STEEK","STEEL","STEEP","STEER","STEMS","STEPS","STERN","STICK","STIFF","STILE","STILL","STILT","STING","STINK","STINT","STOCK","STOIC","STOKE","STOLE","STOMP","STONE","STONY","STOOD","STOOL","STOOP","STORE","STORK","STORM","STORY","STOUT","STOVE","STRAP","STRAW","STRAY","STRIP","STRUT","STUCK","STUDY","STUFF","STUMP","STUNG","STUNK","STUNT","STYLE","SUAVE","SUGAR","SUING","SUITE","SULKY","SULLY","SUMAC","SUNNY","SUPER","SURER","SURGE","SURLY","SUSHI","SWAGE","SWAIN","SWAMP","SWANK","SWANS","SWARM","SWATH","SWEAR","SWEAT","SWEEP","SWEET","SWELL","SWEPT","SWIFT","SWILL","SWINE","SWING","SWIRL","SWISH","SWOON","SWOOP","SWORD","SWORE","SWORN","SWUNG","SYNOD","SYRUP","TABBY","TABLE","TABOO","TACIT","TACKY","TAFFY","TAINT","TAKEN","TAKER","TALON","TAMER","TANGO","TANGY","TAPER","TAPIR","TARDY","TAROT","TASER","TASTE","TASTY","TATTY","TAUNT","TAWNY","TEACH","TEAM","TEARY","TEASE","TEDIOUS","TEEN","TEETH","TEMPO","TENOR","TENSE","TENTH","TEPEE","TEPID","TERRA","TERSE","TEST","THANK","THEFT","THEIR","THEME","THERE","THESE","THETA","THICK","THIEF","THIGH","THING","THINK","THIRD","THONG","THORN","THOSE","THREE","THREW","THROB","THROW","THRUM","THUMB","THUMP","THYME","TIARA","TIBIA","TIDAL","TIGER","TIGHT","TILDE","TIMER","TIMID","TINGE","TIPSY","TITAN","TITLE","TOAST","TODAY","TODDY","TOKEN","TONAL","TONER","TONIC","TOOTH","TOPAZ","TOPIC","TORCH","TORSO","TORUS","TOTAL","TOTEM","TOUCH","TOUGH","TOWER","TOXIC","TOXIN","TRACE","TRACK","TRACT","TRADE","TRAIL","TRAIN","TRAIT","TRAMP","TRASH","TRAWL","TREAD","TREAT","TREND","TRIAD","TRIAL","TRIBE","TRICK","TRIED","TRIER","TRILL","TRIOS","TRIPE","TRITE","TROLL","TROOP","TROTH","TROUT","TROVE","TRUCE","TRUCK","TRUER","TRULY","TRUMP","TRUNK","TRUSS","TRUST","TRUTH","TRYST","TUBER","TULIP","TUMMY","TUNER","TUNIC","TURBO","TUTOR","TWANG","TWEAK","TWEED","TWEET","TWICE","TWIGS","TWILL","TWINE","TWINS","TWIRL","TWIST","TYING","UDDER","ULCER","ULTRA","UMBRA","UNCLE","UNCUT","UNDER","UNDID","UNDUE","UNFED","UNFIT","UNIFY","UNION","UNITE","UNITY","UNLIT","UNMET","UNSET","UNTIE","UNTIL","UNWED","UNZIP","UPPER","UPSET","URBAN","URINE","USAGE","USHER","USING","USUAL","USURP","UTILE","VAGUE","VALID","VALOR","VALUE","VALVE","VAPID","VAULT","VAUNT","VEGAN","VENOM","VENUE","VERGE","VERSE","VERSO","VERVE","VICAR","VIDEO","VIGOR","VILLA","VINYL","VIOLA","VIPER","VIRAL","VIRUS","VISIT","VISOR","VISTA","VITAL","VIVID","VIXEN","VOCAL","VODKA","VOGUE","VOICE","VOID","VOILE","VOTER","VOUCH","VOWEL","VYING","WACKY","WAFER","WAGER","WAGON","WAIST","WAIVE","WALTZ","WARTY","WASHY","WASTE","WATCH","WATER","WAVER","WAXEN","WEARY","WEAVE","WEDGE","WEEDY","WEIGH","WEIRD","WELCH","WELSH","WENCH","WHACK","WHALE","WHARF","WHEAT","WHEEL","WHELP","WHERE","WHICH","WHIFF","WHILE","WHINE","WHINY","WHIRL","WHISK","WHITE","WHOLE","WHOOP","WHOSE","WIDEN","WIDOW","WIDTH","WIELD","WIGHT","WILDC","WILES","WILLY","WIMPS","WINCE","WINCH","WINDY","WINEY","WINGE","WINKY","WIPER","WIRER","WISER","WITCH","WITTY","WIVES","WOKEN","WOMAN","WOMEN","WOODY","WOOER","WOOLY","WOOZY","WORDY","WORLD","WORRY","WORSE","WORST","WORTH","WOULD","WOUND","WOVEN","WRACK","WRATH","WREAK","WRECK","WREST","WRING","WRIST","WRITE","WRONG","WROTE","WRUNG","YACHT","YEARN","YEAST","YIELD","YOGIC","YOUTH","ZEBRA","ZESTY","ZILCH","ZONAL"],
6: [],
7: []
}
};

// 中英文释义 (简版)
const MEAN = {
"APPLE":"苹果","MUSIC":"音乐","HEART":"心脏","DREAM":"梦想","SMILE":"微笑",
"BREAD":"面包","CLOUD":"云","STORM":"风暴","OCEAN":"海洋","RIVER":"河流",
"HOUSE":"房子","WATER":"水","LIGHT":"光","NIGHT":"夜晚","RIGHT":"正确",
"FIRST":"第一","PLACE":"地点","PHONE":"电话","LEARN":"学习","POINT":"要点",
"HAPPY":"快乐","STORY":"故事","LEAVE":"离开","BLACK":"黑色","WHITE":"白色",
"GREEN":"绿色","PLANT":"植物","EARTH":"地球","MAGIC":"魔法","PIANO":"钢琴",
"QUEEN":"女王","TIGER":"老虎","UNITY":"团结","VOICE":"声音","YOUTH":"青春",
"ABOUT":"关于","OTHER":"其他","WHICH":"哪个","THEIR":"他们的","THERE":"那里",
"WORLD":"世界","WOULD":"会","COULD":"能","SHOULD":"应该","ALERT":"警报"
};

// 牛津词典数据 (牛津高阶英汉双解)
// 包含: 音标 / 词性 / 英文释义 / 例句
const DICT = {
  "ABOUT": {
    "p": "/əˈbaʊt/",
    "s": "prep./adv.",
    "e": "on the subject of; concerning\nlocated or happening in or around",
    "ex": "a book about cats"
  },
  "ABOVE": {
    "p": "/əˈbʌv/",
    "s": "prep./adv.",
    "e": "in or to a higher position than",
    "ex": "above the clouds"
  },
  "ABUSE": {
    "p": "/əˈbjuːs/",
    "s": "n./v.",
    "e": "misuse; cruel or violent treatment",
    "ex": "drug abuse"
  },
  "ACTOR": {
    "p": "/ˈæktər/",
    "s": "n.",
    "e": "a person who acts in a play, film, etc.",
    "ex": "a famous actor"
  },
  "ACUTE": {
    "p": "/əˈkjuːt/",
    "s": "adj.",
    "e": "sharp or severe; (of an angle) less than 90°",
    "ex": "acute pain"
  },
  "ADMIT": {
    "p": "/ədˈmɪt/",
    "s": "v.",
    "e": "confess to be true; allow to enter",
    "ex": "admit a mistake"
  },
  "ADOPT": {
    "p": "/əˈdɑːpt/",
    "s": "v.",
    "e": "legally take another's child as one's own; choose",
    "ex": "adopt a new policy"
  },
  "ADULT": {
    "p": "/ˈædʌlt/",
    "s": "n./adj.",
    "e": "a person who is fully grown",
    "ex": "adult education"
  },
  "AFTER": {
    "p": "/ˈæftər/",
    "s": "prep./conj./adv.",
    "e": "during the period following",
    "ex": "after lunch"
  },
  "AGAIN": {
    "p": "/əˈɡen/",
    "s": "adv.",
    "e": "once more; another time",
    "ex": "try again"
  },
  "AGENT": {
    "p": "/ˈeɪdʒənt/",
    "s": "n.",
    "e": "a person who acts on behalf of another",
    "ex": "travel agent"
  },
  "AGREE": {
    "p": "/əˈɡriː/",
    "s": "v.",
    "e": "have the same opinion; consent",
    "ex": "I agree with you"
  },
  "AHEAD": {
    "p": "/əˈhed/",
    "s": "adv.",
    "e": "in front; further forward",
    "ex": "go ahead"
  },
  "ALARM": {
    "p": "/əˈlɑːrm/",
    "s": "n./v.",
    "e": "a warning of danger; a device giving such warning",
    "ex": "fire alarm"
  },
  "ALBUM": {
    "p": "/ˈælbəm/",
    "s": "n.",
    "e": "a blank book for collecting items; a recorded collection",
    "ex": "photo album"
  },
  "ALERT": {
    "p": "/əˈlɜːrt/",
    "s": "adj./n./v.",
    "e": "watchful and prompt; a warning",
    "ex": "stay alert"
  },
  "ALIKE": {
    "p": "/əˈlaɪk/",
    "s": "adj./adv.",
    "e": "similar; in the same way",
    "ex": "they look alike"
  },
  "ALIVE": {
    "p": "/əˈlaɪv/",
    "s": "adj.",
    "e": "living; not dead",
    "ex": "keep hope alive"
  },
  "ALLOW": {
    "p": "/əˈlaʊ/",
    "s": "v.",
    "e": "give permission to; let",
    "ex": "allow me to help"
  },
  "ALONE": {
    "p": "/əˈloʊn/",
    "s": "adj./adv.",
    "e": "without other people; solitary",
    "ex": "live alone"
  },
  "ALONG": {
    "p": "/əˈlɔːŋ/",
    "s": "prep./adv.",
    "e": "moving in a constant direction on",
    "ex": "walk along the road"
  },
  "ALPHA": {
    "p": "/ˈælfə/",
    "s": "n./adj.",
    "e": "the first letter of the Greek alphabet",
    "ex": "alpha and omega"
  },
  "ALTER": {
    "p": "/ˈɔːltər/",
    "s": "v.",
    "e": "change in character or composition",
    "ex": "alter a dress"
  },
  "AMONG": {
    "p": "/əˈmʌŋ/",
    "s": "prep.",
    "e": "situated in the middle of; surrounded by",
    "ex": "among friends"
  },
  "ANGER": {
    "p": "/ˈæŋɡər/",
    "s": "n./v.",
    "e": "a strong feeling of annoyance",
    "ex": "speak in anger"
  },
  "ANGLE": {
    "p": "/ˈæŋɡl/",
    "s": "n.",
    "e": "the space between two intersecting lines",
    "ex": "a sharp angle"
  },
  "ANGRY": {
    "p": "/ˈæŋɡri/",
    "s": "adj.",
    "e": "feeling or showing anger",
    "ex": "an angry customer"
  },
  "APART": {
    "p": "/əˈpɑːrt/",
    "s": "adv.",
    "e": "separated by a distance; to pieces",
    "ex": "stand apart"
  },
  "APPLE": {
    "p": "/ˈæpl/",
    "s": "n.",
    "e": "a round fruit with red, green, or yellow skin",
    "ex": "an apple a day"
  },
  "APPLY": {
    "p": "/əˈplaɪ/",
    "s": "v.",
    "e": "make a formal request; put into operation",
    "ex": "apply for a job"
  },
  "ARENA": {
    "p": "/əˈriːnə/",
    "s": "n.",
    "e": "a level area for sports events",
    "ex": "the sports arena"
  },
  "ARGUE": {
    "p": "/ˈɑːrɡjuː/",
    "s": "v.",
    "e": "give reasons for or against; quarrel",
    "ex": "argue a case"
  },
  "ARISE": {
    "p": "/əˈraɪz/",
    "s": "v.",
    "e": "emerge; become apparent",
    "ex": "problems arise"
  },
  "ARMOR": {
    "p": "/ˈɑːrmər/",
    "s": "n.",
    "e": "a protective covering for the body",
    "ex": "knight's armor"
  },
  "ARRAY": {
    "p": "/əˈreɪ/",
    "s": "n./v.",
    "e": "an impressive display; arrange",
    "ex": "an array of options"
  },
  "ARROW": {
    "p": "/ˈæroʊ/",
    "s": "n.",
    "e": "a weapon with a pointed tip, shot from a bow",
    "ex": "shoot an arrow"
  },
  "ASIDE": {
    "p": "/əˈsaɪd/",
    "s": "adv.",
    "e": "to one side; out of the way",
    "ex": "step aside"
  },
  "ASSET": {
    "p": "/ˈæset/",
    "s": "n.",
    "e": "a useful thing or person",
    "ex": "team asset"
  },
  "ATLAS": {
    "p": "/ˈætləs/",
    "s": "n.",
    "e": "a book of maps",
    "ex": "world atlas"
  },
  "AUDIO": {
    "p": "/ˈɔːdioʊ/",
    "s": "adj./n.",
    "e": "relating to sound reproduction",
    "ex": "audio file"
  },
  "AUDIT": {
    "p": "/ˈɔːdɪt/",
    "s": "n./v.",
    "e": "an official inspection of accounts",
    "ex": "annual audit"
  },
  "AVOID": {
    "p": "/əˈvɔɪd/",
    "s": "v.",
    "e": "keep away from; prevent",
    "ex": "avoid trouble"
  },
  "AWAKE": {
    "p": "/əˈweɪk/",
    "s": "adj./v.",
    "e": "not sleeping; rouse from sleep",
    "ex": "stay awake"
  },
  "BACON": {
    "p": "/ˈbeɪkən/",
    "s": "n.",
    "e": "cured meat from the back or sides of a pig",
    "ex": "bacon and eggs"
  },
  "BADGE": {
    "p": "/bædʒ/",
    "s": "n.",
    "e": "a small piece of metal worn to identify",
    "ex": "name badge"
  },
  "BADLY": {
    "p": "/ˈbædli/",
    "s": "adv.",
    "e": "in an unsatisfactory or incompetent way",
    "ex": "badly hurt"
  },
  "BAGEL": {
    "p": "/ˈbeɪɡəl/",
    "s": "n.",
    "e": "a dense bread roll in the shape of a ring",
    "ex": "cream cheese bagel"
  },
  "BALMY": {
    "p": "/ˈbɑːmi/",
    "s": "adj.",
    "e": "pleasantly warm; mild",
    "ex": "a balmy evening"
  },
  "BANJO": {
    "p": "/ˈbændʒoʊ/",
    "s": "n.",
    "e": "a stringed musical instrument",
    "ex": "play the banjo"
  },
  "BARGE": {
    "p": "/bɑːrdʒ/",
    "s": "n./v.",
    "e": "a long flat-bottomed boat; push forcefully",
    "ex": "barge in"
  },
  "BASIC": {
    "p": "/ˈbeɪsɪk/",
    "s": "adj.",
    "e": "forming an essential foundation; simple",
    "ex": "basic English"
  },
  "BASIN": {
    "p": "/ˈbeɪsn/",
    "s": "n.",
    "e": "a bowl for washing; a region drained by a river",
    "ex": "wash basin"
  },
  "BATHE": {
    "p": "/beɪð/",
    "s": "v.",
    "e": "wash in a bath; swim",
    "ex": "bathe in the sea"
  },
  "BEACH": {
    "p": "/biːtʃ/",
    "s": "n.",
    "e": "a pebbly or sandy shore",
    "ex": "sandy beach"
  },
  "BEARD": {
    "p": "/bɪrd/",
    "s": "n.",
    "e": "hair growing on a man's face",
    "ex": "long beard"
  },
  "BEAST": {
    "p": "/biːst/",
    "s": "n.",
    "e": "an animal, especially a wild one",
    "ex": "wild beast"
  },
  "BEING": {
    "p": "/ˈbiːɪŋ/",
    "s": "n.",
    "e": "existence; a person or creature",
    "ex": "human being"
  },
  "BENCH": {
    "p": "/bentʃ/",
    "s": "n.",
    "e": "a long seat for several people",
    "ex": "park bench"
  },
  "BIBLE": {
    "p": "/ˈbaɪbl/",
    "s": "n.",
    "e": "the Christian scriptures; any authoritative book",
    "ex": "study the Bible"
  },
  "BIRTH": {
    "p": "/bɜːrθ/",
    "s": "n.",
    "e": "the emergence of a baby from the body",
    "ex": "date of birth"
  },
  "BLACK": {
    "p": "/blæk/",
    "s": "adj./n.",
    "e": "of the very darkest color",
    "ex": "black coffee"
  },
  "BLADE": {
    "p": "/bleɪd/",
    "s": "n.",
    "e": "the flat cutting edge of a knife or tool",
    "ex": "razor blade"
  },
  "BLAME": {
    "p": "/bleɪm/",
    "s": "v./n.",
    "e": "assign responsibility for a fault",
    "ex": "don't blame me"
  },
  "BLANK": {
    "p": "/blæŋk/",
    "s": "adj./n.",
    "e": "empty; not filled in",
    "ex": "blank page"
  },
  "BLAST": {
    "p": "/blæst/",
    "s": "n./v.",
    "e": "an explosion; a strong gust",
    "ex": "a blast of wind"
  },
  "BLAZE": {
    "p": "/bleɪz/",
    "s": "n./v.",
    "e": "a very large or fierce fire",
    "ex": "blaze of glory"
  },
  "BLEAK": {
    "p": "/bliːk/",
    "s": "adj.",
    "e": "cold and miserable; not hopeful",
    "ex": "bleak future"
  },
  "BLESS": {
    "p": "/bles/",
    "s": "v.",
    "e": "invoke God's favor upon",
    "ex": "bless you"
  },
  "BLIND": {
    "p": "/blaɪnd/",
    "s": "adj.",
    "e": "unable to see; lacking judgment",
    "ex": "blind person"
  },
  "BLINK": {
    "p": "/blɪŋk/",
    "s": "v./n.",
    "e": "shut and open the eyes quickly",
    "ex": "blink an eye"
  },
  "BLOCK": {
    "p": "/blɑːk/",
    "s": "n./v.",
    "e": "a solid piece of material; obstruct",
    "ex": "block of wood"
  },
  "BLOOD": {
    "p": "/blʌd/",
    "s": "n.",
    "e": "the red liquid in the body",
    "ex": "blood pressure"
  },
  "BLOOM": {
    "p": "/bluːm/",
    "s": "n./v.",
    "e": "a flower; produce flowers",
    "ex": "rose in bloom"
  },
  "BLUE": {
    "p": "/bluː/",
    "s": "adj./n.",
    "e": "of the color of the sky on a clear day",
    "ex": "blue sky"
  },
  "BLUNT": {
    "p": "/blʌnt/",
    "s": "adj.",
    "e": "having a dull edge; frank",
    "ex": "blunt knife"
  },
  "BLURT": {
    "p": "/blɜːrt/",
    "s": "v.",
    "e": "say suddenly and without thinking",
    "ex": "blurt out a secret"
  },
  "BLUSH": {
    "p": "/blʌʃ/",
    "s": "v./n.",
    "e": "turn pink from embarrassment",
    "ex": "blush with shame"
  },
  "BOARD": {
    "p": "/bɔːrd/",
    "s": "n./v.",
    "e": "a flat piece of wood; get on a vehicle",
    "ex": "bulletin board"
  },
  "BOOST": {
    "p": "/buːst/",
    "s": "v./n.",
    "e": "help or encourage; an increase",
    "ex": "boost morale"
  },
  "BOOTH": {
    "p": "/buːθ/",
    "s": "n.",
    "e": "a small temporary structure",
    "ex": "phone booth"
  },
  "BOUND": {
    "p": "/baʊnd/",
    "s": "adj./v.",
    "e": "heading toward; tied",
    "ex": "bound for Paris"
  },
  "BOWEL": {
    "p": "/ˈbaʊəl/",
    "s": "n.",
    "e": "the intestine",
    "ex": "bowel movement"
  },
  "BRAIN": {
    "p": "/breɪn/",
    "s": "n.",
    "e": "the organ of thought inside the head",
    "ex": "brain power"
  },
  "BRAND": {
    "p": "/brænd/",
    "s": "n./v.",
    "e": "a type of product; mark with a brand",
    "ex": "brand name"
  },
  "BRAVE": {
    "p": "/breɪv/",
    "s": "adj.",
    "e": "ready to face danger or pain",
    "ex": "brave soldier"
  },
  "BREAD": {
    "p": "/bred/",
    "s": "n.",
    "e": "a staple food made of flour and water",
    "ex": "slice of bread"
  },
  "BREAK": {
    "p": "/breɪk/",
    "s": "v./n.",
    "e": "separate into pieces; an interval",
    "ex": "take a break"
  },
  "BREED": {
    "p": "/briːd/",
    "s": "v./n.",
    "e": "produce offspring; a variety of animals",
    "ex": "breed cattle"
  },
  "BRIBE": {
    "p": "/braɪb/",
    "s": "n./v.",
    "e": "money offered to influence someone",
    "ex": "bribe a judge"
  },
  "BRICK": {
    "p": "/brɪk/",
    "s": "n.",
    "e": "a small rectangular block used in building",
    "ex": "brick wall"
  },
  "BRIDE": {
    "p": "/braɪd/",
    "s": "n.",
    "e": "a woman on her wedding day",
    "ex": "beautiful bride"
  },
  "BRING": {
    "p": "/brɪŋ/",
    "s": "v.",
    "e": "carry or convey to a place",
    "ex": "bring me water"
  },
  "BRISK": {
    "p": "/brɪsk/",
    "s": "adj.",
    "e": "active and energetic",
    "ex": "brisk walk"
  },
  "BROAD": {
    "p": "/brɔːd/",
    "s": "adj.",
    "e": "wide; general",
    "ex": "broad smile"
  },
  "BROIL": {
    "p": "/brɔɪl/",
    "s": "v.",
    "e": "cook with direct heat",
    "ex": "broil fish"
  },
  "BROKE": {
    "p": "/broʊk/",
    "s": "adj.",
    "e": "having no money",
    "ex": "flat broke"
  },
  "BROOK": {
    "p": "/brʊk/",
    "s": "n./v.",
    "e": "a small stream; tolerate",
    "ex": "brook no argument"
  },
  "BROOM": {
    "p": "/bruːm/",
    "s": "n.",
    "e": "a long-handled sweeping brush",
    "ex": "witch's broom"
  },
  "BROTH": {
    "p": "/brɔːθ/",
    "s": "n.",
    "e": "soup consisting of meat or vegetables in liquid",
    "ex": "chicken broth"
  },
  "BROWN": {
    "p": "/braʊn/",
    "s": "adj./n.",
    "e": "of a color produced by mixing red, yellow, and black",
    "ex": "brown bread"
  },
  "BRUSH": {
    "p": "/brʌʃ/",
    "s": "n./v.",
    "e": "an implement with bristles; apply with a brush",
    "ex": "paint brush"
  },
  "BUDDY": {
    "p": "/ˈbʌdi/",
    "s": "n.",
    "e": "a close friend",
    "ex": "buddies forever"
  },
  "BUDGET": {
    "p": "/ˈbʌdʒɪt/",
    "s": "n.",
    "e": "an estimate of income and expenditure",
    "ex": "tight budget"
  },
  "BUILD": {
    "p": "/bɪld/",
    "s": "v.",
    "e": "construct by putting parts together",
    "ex": "build a house"
  },
  "BUILT": {
    "p": "/bɪlt/",
    "s": "adj.",
    "e": "constructed; made",
    "ex": "well-built"
  },
  "BUNCH": {
    "p": "/bʌntʃ/",
    "s": "n.",
    "e": "a number of things grouped together",
    "ex": "bunch of flowers"
  },
  "BURST": {
    "p": "/bɜːrst/",
    "s": "v./n.",
    "e": "break open suddenly; an outbreak",
    "ex": "burst into tears"
  },
  "BUTCH": {
    "p": "/bʊtʃ/",
    "s": "adj.",
    "e": "having a tough, masculine appearance",
    "ex": "butch haircut"
  },
  "BUYER": {
    "p": "/ˈbaɪər/",
    "s": "n.",
    "e": "a person who buys",
    "ex": "home buyer"
  },
  "CABIN": {
    "p": "/ˈkæbɪn/",
    "s": "n.",
    "e": "a small shelter; a private room on a ship",
    "ex": "log cabin"
  },
  "CABLE": {
    "p": "/ˈkeɪbl/",
    "s": "n.",
    "e": "a thick rope of wire; a telegram",
    "ex": "cable TV"
  },
  "CANDY": {
    "p": "/ˈkændi/",
    "s": "n.",
    "e": "a sweet food made with sugar",
    "ex": "candy store"
  },
  "CANOE": {
    "p": "/kəˈnuː/",
    "s": "n.",
    "e": "a narrow boat propelled by paddles",
    "ex": "paddle a canoe"
  },
  "CAROL": {
    "p": "/ˈkærəl/",
    "s": "n.",
    "e": "a religious folk song or hymn",
    "ex": "Christmas carol"
  },
  "CARRY": {
    "p": "/ˈkæri/",
    "s": "v.",
    "e": "support and move from one place to another",
    "ex": "carry a bag"
  },
  "CASTE": {
    "p": "/kæst/",
    "s": "n.",
    "e": "a social class system",
    "ex": "caste system"
  },
  "CAUSE": {
    "p": "/kɔːz/",
    "s": "n./v.",
    "e": "a person or thing that makes something happen",
    "ex": "cause of death"
  },
  "CEASE": {
    "p": "/siːs/",
    "s": "v.",
    "e": "stop; come to an end",
    "ex": "cease fire"
  },
  "CHAIN": {
    "p": "/tʃeɪn/",
    "s": "n./v.",
    "e": "a series of connected links; fasten",
    "ex": "chain of events"
  },
  "CHAIR": {
    "p": "/tʃer/",
    "s": "n.",
    "e": "a separate seat for one person",
    "ex": "sit in a chair"
  },
  "CHARM": {
    "p": "/tʃɑːrm/",
    "s": "n./v.",
    "e": "the power to delight; attractiveness",
    "ex": "lucky charm"
  },
  "CHART": {
    "p": "/tʃɑːrt/",
    "s": "n.",
    "e": "a sheet of information in diagram form",
    "ex": "flow chart"
  },
  "CHASE": {
    "p": "/tʃeɪs/",
    "s": "v./n.",
    "e": "pursue in order to catch",
    "ex": "chase a thief"
  },
  "CHEAP": {
    "p": "/tʃiːp/",
    "s": "adj.",
    "e": "low in price; of poor quality",
    "ex": "cheap hotel"
  },
  "CHEAT": {
    "p": "/tʃiːt/",
    "s": "v./n.",
    "e": "act dishonestly to gain advantage",
    "ex": "cheat on a test"
  },
  "CHECK": {
    "p": "/tʃek/",
    "s": "v./n.",
    "e": "examine; a pattern of squares",
    "ex": "check your work"
  },
  "CHEER": {
    "p": "/tʃɪr/",
    "s": "v./n.",
    "e": "shout for joy; a cry of approval",
    "ex": "cheer up"
  },
  "CHESS": {
    "p": "/tʃes/",
    "s": "n.",
    "e": "a board game for two players",
    "ex": "play chess"
  },
  "CHIEF": {
    "p": "/tʃiːf/",
    "s": "n./adj.",
    "e": "a leader; most important",
    "ex": "chief executive"
  },
  "CHILD": {
    "p": "/tʃaɪld/",
    "s": "n.",
    "e": "a young human being below the age of puberty",
    "ex": "child care"
  },
  "CHILL": {
    "p": "/tʃɪl/",
    "s": "n./v.",
    "e": "a moderate coldness; make cool",
    "ex": "chill out"
  },
  "CHINA": {
    "p": "/ˈtʃaɪnə/",
    "s": "n.",
    "e": "fine ceramic ware",
    "ex": "china cup"
  },
  "CHIP": {
    "p": "/tʃɪp/",
    "s": "n.",
    "e": "a small piece broken off; a fried potato slice",
    "ex": "potato chip"
  },
  "CHOIR": {
    "p": "/ˈkwaɪər/",
    "s": "n.",
    "e": "an organized group of singers",
    "ex": "church choir"
  },
  "CHORD": {
    "p": "/kɔːrd/",
    "s": "n.",
    "e": "a group of notes played together",
    "ex": "play a chord"
  },
  "CHOSE": {
    "p": "/tʃoʊz/",
    "s": "v.",
    "e": "past tense of choose",
    "ex": "she chose well"
  },
  "CHUNK": {
    "p": "/tʃʌŋk/",
    "s": "n.",
    "e": "a thick solid piece",
    "ex": "chunk of meat"
  },
  "CIVIL": {
    "p": "/ˈsɪvl/",
    "s": "adj.",
    "e": "relating to citizens; polite",
    "ex": "civil war"
  },
  "CLASH": {
    "p": "/klæʃ/",
    "s": "v./n.",
    "e": "disagree strongly; conflict",
    "ex": "clash with police"
  },
  "CLASS": {
    "p": "/klæs/",
    "s": "n.",
    "e": "a set with common attributes; a lesson",
    "ex": "business class"
  },
  "CLEAN": {
    "p": "/kliːn/",
    "s": "adj./v.",
    "e": "free from dirt; make clean",
    "ex": "clean water"
  },
  "CLEAR": {
    "p": "/klɪr/",
    "s": "adj./v.",
    "e": "easy to perceive; remove obstructions",
    "ex": "clear sky"
  },
  "CLICK": {
    "p": "/klɪk/",
    "s": "v./n.",
    "e": "a short sharp sound; press a button",
    "ex": "click here"
  },
  "CLIFF": {
    "p": "/klɪf/",
    "s": "n.",
    "e": "a steep rock face",
    "ex": "cliff edge"
  },
  "CLIMB": {
    "p": "/klaɪm/",
    "s": "v.",
    "e": "go up; ascend",
    "ex": "climb a mountain"
  },
  "CLING": {
    "p": "/klɪŋ/",
    "s": "v.",
    "e": "hold tightly; refuse to let go",
    "ex": "cling to hope"
  },
  "CLOCK": {
    "p": "/klɑːk/",
    "s": "n.",
    "e": "a device for measuring time",
    "ex": "wall clock"
  },
  "CLOSE": {
    "p": "/kloʊz/",
    "s": "v./adj.",
    "e": "shut; near; intimate",
    "ex": "close the door"
  },
  "CLOTH": {
    "p": "/klɔːθ/",
    "s": "n.",
    "e": "woven fabric",
    "ex": "table cloth"
  },
  "CLOUD": {
    "p": "/klaʊd/",
    "s": "n.",
    "e": "a visible mass of water vapor in the sky",
    "ex": "rain cloud"
  },
  "CLOWN": {
    "p": "/klaʊn/",
    "s": "n.",
    "e": "a comic entertainer",
    "ex": "circus clown"
  },
  "CLUE": {
    "p": "/kluː/",
    "s": "n.",
    "e": "a piece of evidence that leads to a solution",
    "ex": "find a clue"
  },
  "CLUMP": {
    "p": "/klʌmp/",
    "s": "n.",
    "e": "a clustered mass",
    "ex": "clump of trees"
  },
  "COAST": {
    "p": "/koʊst/",
    "s": "n./v.",
    "e": "land near the sea; move without effort",
    "ex": "Pacific coast"
  },
  "COAT": {
    "p": "/koʊt/",
    "s": "n.",
    "e": "an outer garment with sleeves",
    "ex": "winter coat"
  },
  "CODE": {
    "p": "/koʊd/",
    "s": "n.",
    "e": "a system of words, letters, or symbols",
    "ex": "secret code"
  },
  "COIN": {
    "p": "/kɔɪn/",
    "s": "n.",
    "e": "a flat disc of metal used as money",
    "ex": "gold coin"
  },
  "COLD": {
    "p": "/koʊld/",
    "s": "adj./n.",
    "e": "of low temperature; common cold",
    "ex": "cold weather"
  },
  "COLOR": {
    "p": "/ˈkʌlər/",
    "s": "n.",
    "e": "the property of an object that produces sensations on the eye",
    "ex": "bright color"
  },
  "COMET": {
    "p": "/ˈkɑːmɪt/",
    "s": "n.",
    "e": "a celestial body with a tail",
    "ex": "Halley's comet"
  },
  "COMIC": {
    "p": "/ˈkɑːmɪk/",
    "s": "adj./n.",
    "e": "causing laughter; a comedian",
    "ex": "comic book"
  },
  "CORAL": {
    "p": "/ˈkɔːrəl/",
    "s": "n.",
    "e": "a hard substance formed by sea creatures",
    "ex": "coral reef"
  },
  "COUCH": {
    "p": "/kaʊtʃ/",
    "s": "n.",
    "e": "a long upholstered seat for two or more",
    "ex": "leather couch"
  },
  "COUGH": {
    "p": "/kɔːf/",
    "s": "v./n.",
    "e": "expel air from the lungs abruptly",
    "ex": "dry cough"
  },
  "COULD": {
    "p": "/kʊd/",
    "s": "modal",
    "e": "past of can: ability, possibility, permission",
    "ex": "I could go"
  },
  "COUNT": {
    "p": "/kaʊnt/",
    "s": "v./n.",
    "e": "determine the number; a nobleman",
    "ex": "count to ten"
  },
  "COURT": {
    "p": "/kɔːrt/",
    "s": "n.",
    "e": "a tribunal for civil and criminal cases",
    "ex": "supreme court"
  },
  "COVER": {
    "p": "/ˈkʌvər/",
    "s": "v./n.",
    "e": "put something over; a lid",
    "ex": "book cover"
  },
  "CRACK": {
    "p": "/kræk/",
    "s": "n./v.",
    "e": "a narrow opening; break without separation",
    "ex": "crack an egg"
  },
  "CRAFT": {
    "p": "/kræft/",
    "s": "n./v.",
    "e": "a skilled trade; make skillfully",
    "ex": "arts and crafts"
  },
  "CRANE": {
    "p": "/kreɪn/",
    "s": "n.",
    "e": "a large tall machine for lifting; a bird",
    "ex": "construction crane"
  },
  "CRASH": {
    "p": "/kræʃ/",
    "s": "v./n.",
    "e": "collide violently; a loud noise",
    "ex": "car crash"
  },
  "CRAVE": {
    "p": "/kreɪv/",
    "s": "v.",
    "e": "feel a powerful desire for",
    "ex": "crave chocolate"
  },
  "CRAWL": {
    "p": "/krɔːl/",
    "s": "v.",
    "e": "move on hands and knees",
    "ex": "baby crawl"
  },
  "CRAZY": {
    "p": "/ˈkreɪzi/",
    "s": "adj.",
    "e": "mad; foolish",
    "ex": "crazy idea"
  },
  "CREAM": {
    "p": "/kriːm/",
    "s": "n.",
    "e": "the fatty part of milk; a pale yellow color",
    "ex": "ice cream"
  },
  "CREED": {
    "p": "/kriːd/",
    "s": "n.",
    "e": "a system of religious belief",
    "ex": "creed of faith"
  },
  "CREEK": {
    "p": "/kriːk/",
    "s": "n.",
    "e": "a small stream",
    "ex": "fishing creek"
  },
  "CREEP": {
    "p": "/kriːp/",
    "s": "v.",
    "e": "move slowly and carefully",
    "ex": "creep up on"
  },
  "CREPE": {
    "p": "/kreɪp/",
    "s": "n.",
    "e": "a thin pancake; a crinkled fabric",
    "ex": "crepe paper"
  },
  "CREST": {
    "p": "/krest/",
    "s": "n.",
    "e": "a plume on a helmet; the top of a wave",
    "ex": "family crest"
  },
  "CRIME": {
    "p": "/kraɪm/",
    "s": "n.",
    "e": "an illegal act",
    "ex": "violent crime"
  },
  "CRISP": {
    "p": "/krɪsp/",
    "s": "adj.",
    "e": "firm and dry; sharp and clear",
    "ex": "crisp apple"
  },
  "CROSS": {
    "p": "/krɔːs/",
    "s": "n./v.",
    "e": "a symbol of Christianity; go across",
    "ex": "red cross"
  },
  "CROWD": {
    "p": "/kraʊd/",
    "s": "n.",
    "e": "a large number of people gathered",
    "ex": "large crowd"
  },
  "CROWN": {
    "p": "/kraʊn/",
    "s": "n.",
    "e": "a circular headdress worn by a monarch",
    "ex": "queen's crown"
  },
  "CRUDE": {
    "p": "/kruːd/",
    "s": "adj.",
    "e": "in a natural state; vulgar",
    "ex": "crude oil"
  },
  "CRUEL": {
    "p": "/ˈkruːəl/",
    "s": "adj.",
    "e": "causing pain or suffering",
    "ex": "cruel punishment"
  },
  "CRUSH": {
    "p": "/krʌʃ/",
    "s": "v./n.",
    "e": "compress with force; infatuation",
    "ex": "crush ice"
  },
  "CRUST": {
    "p": "/krʌst/",
    "s": "n.",
    "e": "the outer layer of bread or pastry",
    "ex": "pie crust"
  },
  "CRYPT": {
    "p": "/krɪpt/",
    "s": "n.",
    "e": "an underground room used as a burial place",
    "ex": "ancient crypt"
  },
  "CUBIC": {
    "p": "/ˈkjuːbɪk/",
    "s": "adj.",
    "e": "having the shape of a cube",
    "ex": "cubic meter"
  },
  "CURLY": {
    "p": "/ˈkɜːrli/",
    "s": "adj.",
    "e": "forming curls",
    "ex": "curly hair"
  },
  "CURRY": {
    "p": "/ˈkɜːri/",
    "s": "n.",
    "e": "a dish of meat or vegetables in spiced sauce",
    "ex": "chicken curry"
  },
  "CURSE": {
    "p": "/kɜːrs/",
    "s": "n./v.",
    "e": "a magical invocation; swear word",
    "ex": "put a curse on"
  },
  "CYCLE": {
    "p": "/ˈsaɪkl/",
    "s": "n./v.",
    "e": "a series of events; ride a bicycle",
    "ex": "life cycle"
  }
};

